### ISSUE TITLE
 java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference

### ISSUE THREAD

**Issue by tangyichao** [airbnb/lottie-android#796] opened 2018-06-07 06:33 UTC
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
        at android.graphics.Path.setFillType(Path.java:240)
        at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:62)
        at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:80)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
        at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
        at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
        at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:236)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:198)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:484)
        at $3.onCompositionLoaded
        at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
        at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)
        at android.os.AsyncTask.finish(AsyncTask.java:651)
        at android.os.AsyncTask.access$500(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by gpeal** [comment] 2018-06-07 22:46
Duplicate of #772

**Closed by gpeal** 2018-06-07 22:46 UTC

**Comment by behnamdarzi** [comment] 2018-07-10 04:03
hi guys, I have the same error while trying to share a text using the class rakroidsend
what is the reason?
