### ISSUE TITLE
TextDelegate still not supported for Compose

### ISSUE THREAD

**Issue by MurilloMaciel** [airbnb/lottie-android#1908] opened 2021-09-24 19:53 UTC
**Is your feature request related to a problem? Please describe.**
I'm having troubles trying to change dynamically some texts of my json animation.
In old ways, with View, we had TextDelegate to handle this problem, but for Lottie in JetPack Compose we still doesn't.

**Describe the solution you'd like**
I would like a similar approach of TextDelegate for JetPack Compose.

**Describe alternatives you've considered**
I've considered the actual TextDelegate, but I couldn't make it work.

**Additional context**
Nothing to add here.

**Comment by gpeal** [comment] 2021-11-03 05:45
Duplicate of #1903

**Closed by gpeal** 2021-11-03 05:45 UTC
Labels: New feature
