### ISSUE TITLE
NullPointerException--phone model:Micromax A120,lottie version 2.3.0

### ISSUE THREAD

**Issue by magic1983** [airbnb/lottie-android#541] opened 2017-11-28 06:53 UTC
Fatal Exception: java.lang.NullPointerException
       at com.airbnb.lottie.model.layer.CompositionLayer.(CompositionLayer.java)
       at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:201)
       at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:164)
       at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:386)
       at com.airbnb.lottie.LottieAnimationView$2.onCompositionLoaded(LottieAnimationView.java:351)
       at com.airbnb.lottie.model.FileCompositionLoader.onPostExecute(FileCompositionLoader.java:24)
       at com.airbnb.lottie.model.FileCompositionLoader.onPostExecute(FileCompositionLoader.java:10)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by gpeal** [comment] 2017-11-28 18:56
@magic1983 You're on 2.2.5 not 2.3.0 based on the line numbers in your stack trace.
Can you attach the animation that crashes? We haven't seen this.

**Comment by gpeal** [comment] 2017-11-28 22:17
Duplicate of #524

**Closed by gpeal** 2017-11-28 22:17 UTC
