### ISSUE TITLE
Lottie JSON Animation Crashing

### ISSUE THREAD

**Issue by twobirabiron** [airbnb/lottie-android#1179] opened 2019-04-10 18:36 UTC
Guys, I'm using an animation and it's crashing all the time. What could it be?

Process: sb.merchant, PID: 25373
    java.lang.IllegalStateException: Missing values for keyframe.
        at com.airbnb.lottie.animation.keyframe.FloatKeyframeAnimation.getValue(FloatKeyframeAnimation.java:16)
        at com.airbnb.lottie.animation.keyframe.FloatKeyframeAnimation.getValue(FloatKeyframeAnimation.java:8)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
        at com.airbnb.lottie.utils.Utils.applyTrimPathIfNeeded(Utils.java:71)
        at com.airbnb.lottie.animation.content.ShapeContent.getPath(ShapeContent.java:64)
        at com.airbnb.lottie.animation.content.BaseStrokeContent.draw(BaseStrokeContent.java:160)
        at com.airbnb.lottie.animation.content.StrokeContent.draw(StrokeContent.java:36)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
        at com.airbnb.lottie.animation.content.ContentGroup.draw(ContentGroup.java:161)
        at com.airbnb.lottie.model.layer.ShapeLayer.drawLayer(ShapeLayer.java:30)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:300)
        at android.widget.ImageView.onDraw(ImageView.java:1380)
        at android.view.View.draw(View.java:19200)
        at android.view.View.updateDisplayListIfDirty(View.java:18150)
        at android.view.View.draw(View.java:18928)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
        at android.view.View.draw(View.java:19203)
        at android.view.View.updateDisplayListIfDirty(View.java:18150)
        at android.view.View.draw(View.java:18928)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
        at android.view.View.updateDisplayListIfDirty(View.java:18141)
        at android.view.View.draw(View.java:18928)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
        at android.view.View.updateDisplayListIfDirty(View.java:18141)
        at android.view.View.draw(View.java:18928)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4026)
        at android.view.View.draw(View.java:19203)
        at com.android.internal.policy.DecorView.draw(DecorView.java:817)
        at android.view.View.updateDisplayListIfDirty(View.java:18150)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3020)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2834)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2387)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1420)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6835)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6647)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by gpeal** [comment] 2019-04-11 12:33
Duplicate of https://github.com/airbnb/lottie-android/issues/1177

**Comment by gpeal** [comment] 2019-04-11 12:33
In short: upgrade to 3.0

**Closed by gpeal** 2019-04-11 12:33 UTC

**Comment by twobirabiron** [comment] 2019-04-11 18:28
Thanks @gpeal  a lot! I'm gonna upgrade and check it out.

**Comment by ganeshpadhayay** [comment] 2019-04-16 07:44
Can we somehow catch this exception in our code?? any listener for this???

**Comment by gpeal** [comment] 2019-04-17 18:48
@ganeshpadhayay You need to upgrade Lottie or check the setting for compatibility mode in Bodymovin. It will never succeed otherwise.
