### ISSUE TITLE
Lottie adds wrong shadows on small dpi devices 

### ISSUE THREAD

**Issue by SemenovAlexander** [airbnb/lottie-android#1313] opened 2019-07-11 11:53 UTC
We have an issue with one file, which reproduces on devices with small screen density (hdpi).
Lottie draws something like a shadow, where it shouldn't be. 
See the demo project with screenshots:
https://github.com/SemenovAlexander/LottieSmallDevicesBug

The issue occurs on all Lottie versions after `3.0.0-beta2`.
If I switch project to`3.0.0-beta2` - everything works fine.

![Screenshot_1562845027](https://user-images.githubusercontent.com/6439273/61048882-c9375700-a3eb-11e9-8178-42b9197b9b8a.png)

**Comment by gpeal** [comment] 2019-07-15 17:58
Duplicate of #1287

**Closed by gpeal** 2019-07-15 17:58 UTC
