### ISSUE TITLE
more restores than saves

### ISSUE THREAD

**Issue by caiyoufei** [airbnb/lottie-android#1071] opened 2018-12-26 04:19 UTC
lottie version 2.5.5
![image](https://user-images.githubusercontent.com/11989916/50431784-59a6c200-0908-11e9-85e4-d9dd885a5aa3.png)

**Comment by panzhi1** [comment] 2018-12-27 07:17
if you use  lottieAnimatedView.draw(canvas) ,it mus must be used on UI thread .

**Comment by gpeal** [comment] 2018-12-31 22:58
@caiyoufei Can you attach your animation?

**Comment by akshaymathur90** [comment] 2019-01-21 18:41
I am also getting the same crash, only on **Huawei phones** running **Android 9**
Lottie Version: 2.5.5

java.lang.IllegalStateException: Underflow in restore - more restores than saves
	at android.graphics.Canvas.restore(Canvas.java:605)
	at com.airbnb.lottie.model.layer.CompositionLayer.b(CompositionLayer.java:75)
	at com.airbnb.lottie.model.layer.BaseLayer.a(BaseLayer.java:127)
	at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:99)
	at android.widget.ImageView.onDraw(ImageView.java:1458)
	at android.view.View.draw(View.java:20509)
	at android.view.View.buildDrawingCacheImpl(View.java:19722)
	at android.view.View.buildDrawingCache(View.java:19576)
	at android.view.View.draw(View.java:20229)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4394)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4170)
	at android.view.View.draw(View.java:20512)
	at android.view.View.updateDisplayListIfDirty(View.java:19320)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4375)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4348)
	at android.view.View.updateDisplayListIfDirty(View.java:19280)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:729)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:735)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:850)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3586)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3370)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2701)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1624)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7926)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1079)
	at android.view.Choreographer.doCallbacks(Choreographer.java:885)
	at android.view.Choreographer.doFrame(Choreographer.java:809)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1065)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7470)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by gpeal** [comment] 2019-01-31 01:43
@caiyoufei @akshaymathur90 Are you both seeing this exclusively on Huawei phones running P?

**Comment by akshaymathur90** [comment] 2019-01-31 17:08
@gpeal Yes, We are seeing this exclusively on Huawei and Honor Devices running Android P.

**Comment by gpeal** [comment] 2019-02-01 01:56
@akshaymathur90 Do you have any test devices you can test with yourself? It's not easy for me to get a hold of one of them.

**Comment by gpeal** [comment] 2019-02-02 20:04
@akshaymathur90 Okay, if you get a hold of one and are able to reproduce, I may ask for your help debugging here as the code should run exactly the same on different devices.

**Comment by gpeal** [comment] 2019-02-02 20:04
@akshaymathur90 Also, try disabling hardware acceleration if you have turned it on.

**Comment by akshaymathur90** [comment] 2019-02-05 22:04
@gpeal i was able to reproduce the issue on a Huawei P20 Pro running Android P with a Test App containing the animation. 
Along with the above mentioned crash i saw the below Native crash. I have attached the logs

[Huawei_Native_Crash.txt](https://github.com/airbnb/lottie-android/files/2834064/Huawei_Native_Crash.txt)

Also hardware acceleration is turned off.

**Comment by gpeal** [comment] 2019-02-05 22:23
@akshaymathur90 Interesting. Does this happen 100% of the time?
I could really use your help here if you have some time to help debug this.
It would be great if you could pare down the animation until you can find the exact root part of the animation that is causing the crash.

**Comment by akshaymathur90** [comment] 2019-02-05 23:06
@gpeal Yes, it happens 100% of the time. I can work with you to debug this. 
let me nail down the root part of the animation.

**Comment by gpeal** [comment] 2019-02-06 00:52
@akshaymathur90 Thank you very much!

**Comment by akshaymathur90** [comment] 2019-02-06 23:13
@gpeal I took the latest source code from github and imported it in my project. The app does not crash anymore on Huawei phone while playing the animations. Do you know when the next version will be released? Also, what would have fixed the issue?

**Comment by gpeal** [comment] 2019-02-07 16:15
@akshaymathur90 Hah, that's great! Quite a lot has changed under the hood but the biggest one is that it saves and restores a much smaller surface area when you use masks and mattes which has a huge performance and memory benefit. Does your animation have masks or mattes?

I'll be releasing an rc in the coming weeks. However, beta1 is very stable and passes all tests so you may upgrade if you want to resolve this crash.

I'll close this issue since it's resolved.

**Closed by gpeal** 2019-02-07 16:15 UTC
