### ISSUE TITLE
Unable to parse composition

### ISSUE THREAD

**Issue by MohammedAbidNafi** [airbnb/lottie-android#2398] opened 2023-10-17 13:20 UTC
Process: com.hacktivators.mentalhealth, PID: 3805
                                                                                                    java.lang.IllegalStateException: Unable to parse composition
                                                                                                    	at com.airbnb.lottie.LottieAnimationView.lambda$static$0(LottieAnimationView.java:75)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$$ExternalSyntheticLambda1.onResult(Unknown Source:2)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$WeakFailureListener.onResult(LottieAnimationView.java:117)
                                                                                                    	at com.airbnb.lottie.LottieAnimationView$WeakFailureListener.onResult(LottieAnimationView.java:99)
                                                                                                    	at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:162)
                                                                                                    	at com.airbnb.lottie.LottieTask.lambda$notifyListeners$0$com-airbnb-lottie-LottieTask(LottieTask.java:138)
                                                                                                    	at com.airbnb.lottie.LottieTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Unable to parse composition
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromZipStreamSyncInternal(LottieCompositionFactory.java:573)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromZipStreamSync(LottieCompositionFactory.java:509)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromZipStreamSync(LottieCompositionFactory.java:493)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:288)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory.lambda$fromRawRes$2(LottieCompositionFactory.java:256)
                                                                                                    	at com.airbnb.lottie.LottieCompositionFactory$$ExternalSyntheticLambda8.call(Unknown Source:8)

**Comment by MohammedAbidNafi** [comment] 2023-10-21 21:11
https://lottie.host/f2eb4296-a845-441c-a61d-cdc4905e9c2b/gP4NOedPsP.json

But not only in this json file its happening with many of the json file but if I use any json file from my old project it is working only newly downloaded ones are giving this error

**Comment by gpeal** [comment] 2023-10-30 02:49
This is because `to` and `ti` are null for some of the shapes. I haven't seen this in an animation before and I don't think this is expected behavior and may indicate a bug in the AE plugin. I'll check with the team though.

**Comment by gpeal** [comment] 2023-10-30 04:02
Duplicate of #2399

**Closed by gpeal** 2023-10-30 04:02 UTC
Labels: Needs more info

**Comment by graceful1372** [comment] 2024-07-08 09:15
Hello
When this topic is closed, is this problem solved or not?
Because I have this problem and I can't find a solution for it

**Comment by heihitesh** [comment] 2024-12-23 15:52
I have the same problem, I see that some device this issue is occurring
