### ISSUE TITLE
Alpha channel not applied to the layer with mode=Multiply

### ISSUE THREAD

**Issue by mateuszkwiecinski** [airbnb/lottie-android#2306] opened 2023-06-05 16:26 UTC
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features). 

I don't know for sure, but it works on web and iOS and I don't believe this relies on Skew transformation

2. I know what part of my animation doesn't work.

I know ✅ 

3. I have created a simplified version of my animation 

I did ✅ 

4. I have attached the AEP file (as a zip file, so it can be attached) that only has the part of the animation that doesn't work.

I did ✅ 

**Describe the bug**
AEP: [repro.aep.zip](https://github.com/airbnb/lottie-android/files/11654623/repro.aep.zip)
Animation JSON: [repro.json.zip](https://github.com/airbnb/lottie-android/files/11654665/repro.json.zip)

The following animation renders differently on Android when compared with Web and iOS clients (see screenshot below)

I hope there isn't an obvious reason why this doesn't work. I tried to go through the documentation, but I quickly get lost in what _layer_ or _shape_ means in the context. This is the first time I see Adobe After Effect software 😅 

**What version of Lottie did you test this on?**
`5.0.1`

**What version of Android did you test this on?**
API level 26 and 33

**Steps To Reproduce**
Steps to reproduce the behavior: I'm not sure how this is unique 🤷 I haven't created the resource, and I don't see anything obvious there. I don't see any transition or anything like that applied.
I tried shooting in the dark and used the `Merge Paths` and `Apply Opacity to Layers` option, but I don't see any difference in how the animation behaves 👀 

**Screenshots**

|Web & iOS|Android|
|---|---|
|![image](https://github.com/airbnb/lottie-android/assets/36954793/6deb222a-8834-441a-b53e-a252cdcb773b)|![image](https://github.com/airbnb/lottie-android/assets/36954793/5b23b5b5-2f7c-4f11-a2f9-28b9621b8c62)|

**Comment by mateuszkwiecinski** [comment] 2023-06-05 17:59
After another round of debugging, it looks like the not-working part is the `Mode=Multiply` toggle?
![image](https://github.com/airbnb/lottie-android/assets/36954793/3b56c250-0940-4c7b-a203-5f0b82b44fcd)

but again, I'm shooting in the dark. I'm just clicking random stuff in After Effect and see what happens 😅 

The documentation seems to mention Multiply mode once: https://airbnb.io/lottie/#/after-effects?id=no-blending-modes-or-luma-mattes as a limitation of `BodyMovin` plugin, which doesn't seem to be applicable here since a) I used the "LottieFiles for After Effects" plugin, b) the animation works on iOS (which I interpreted as "it exports correctly).

**Comment by gpeal** [comment] 2023-06-11 00:58
@mateuszkwiecinski the Lottiefiles plugin just wraps the bodymovin plugin so the limitations are the same. My guess is that iOS actually isn't rendering this correctly but may be failing more gracefully.

**Comment by mateuszkwiecinski** [comment] 2023-06-12 08:21
Thanks for reply 🙏 Here's a recording from iOS demo app: 

https://github.com/airbnb/lottie-android/assets/36954793/c236950a-7f76-4a19-a755-01f9d9204d14

Looks like iOS fully supports the feature, as the result is exactly the same as on Web client. 

Also, one thing I realized I don't fully get: if this is a _bodymovin_ limitation, why would other platforms (Web & iOS) handle the same output resource correctly, shouldn't After Effect's plugin limitation affect all platforms? 🤔

**Comment by gpeal** [comment] 2023-07-16 17:44
Duplicate of #1055

**Closed by gpeal** 2023-07-16 17:44 UTC
Labels: Rendering bug
