### ISSUE TITLE
NullPointerException occurs because of the json item order

### ISSUE THREAD

**Issue by onurkoncaoglu** [airbnb/lottie-android#1904] opened 2021-09-21 14:33 UTC
Hi there,

One of our lottie animation was giving us a strange NullPointerException which is rendering successfully in a web browser preview or ios.

java.lang.NullPointerException: Attempt to invoke virtual method 'com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation com.airbnb.lottie.model.animatable.AnimatableColorValue.createAnimation()' on a null object reference

I debug it and saw that ShapeStroke's color returns null in StrokeContent line:35 (library version 4.1.0)

I reviewed the json file and show that {"ty": "st"} properties are affect that class. I compare stroke elements of json files with others and saw that the only difference is order of the "ty": "st" element in a json object.

Normally, the order of the json element doesn't matter but in this situation it affects. 

I could render and play the animation successfully when I put the "ty" element in the first place.

Could you check and fix it?

Example (not rendered, color comes null):
```
{
	"c": {
		"a": 0,
		"k": [
			0.15294117647058825,
			0.6588235294117647,
			0.8823529411764706,
			1
		],
		"ix": 3
	},
	"bm": 0,
	"ty": "st",
	"o": {
		"a": 0,
		"k": 100,
		"ix": 4
	},
	"w": {
		"a": 0,
		"k": 8,
		"ix": 5
	},
	"lc": 2,
	"hd": false,
	"lj": 1,
	"ml": 4,
	"nm": "Stroke 1"
}
```

Example (successfully rendered):
```
{
	"ty": "st",
	"c": {
		"a": 0,
		"k": [
			0.15294117647058825,
			0.6588235294117647,
			0.8823529411764706,
			1
		],
		"ix": 3
	},
	"bm": 0,
	"o": {
		"a": 0,
		"k": 100,
		"ix": 4
	},
	"w": {
		"a": 0,
		"k": 8,
		"ix": 5
	},
	"lc": 2,
	"hd": false,
	"lj": 1,
	"ml": 4,
	"nm": "Stroke 1"
}
```

Android Library: 4.1.0

**Comment by gpeal** [comment] 2021-09-21 21:34
Duplicate of #1529

**Closed by gpeal** 2021-09-21 21:34 UTC
Labels: Rendering bug

**Comment by onurkoncaoglu** [comment] 2021-09-22 10:06
I assume that there is a performance concerns, but this causes incompatibility with other platforms. Web and iOS SDK renders successfully (like json specs, object key-value pairs order doesn't matters)

Of course the decision is yours, I just wanted to inform
