### ISSUE TITLE
Overlapping shapes with opacity keyframe fades have an artifact where overlapped

### ISSUE THREAD

**Issue by jeffsteinmetz** [airbnb/lottie-android#606] opened 2018-01-29 02:56 UTC
Works on iOS
opacity fades show overlap on Android
(ignore the gradient background in this screen capture, the test was the overlapping circles)
<img width="264" alt="android_emulator_-_nexus_5_api_26_5554" src="https://user-images.githubusercontent.com/5488059/34169743-3aef4d7c-e49d-11e7-9f38-5b3ccae75f15.png">

Attaching .json and After Effects

This example uses a child composition with overlapping circles, and fades that comp in the main composition.

[fade-animation-example.zip](https://github.com/airbnb/lottie-react-native/files/1572584/fade-animation-example.zip)

**Comment by gpeal** [comment] 2018-01-30 07:32
Duplicate of #223

**Closed by gpeal** 2018-01-30 07:32 UTC

**Comment by taylorling** [comment] 2018-02-05 13:35
@gpeal I think I might have the same issue, and I am using pre-comp. The opacity change in the comp renders correctly in web and iOS, but in Android, it has this overlapping transparent effect.

Attached below is the comparison of iOS and Android:
![media-20180205](https://user-images.githubusercontent.com/7766387/35806994-58ec98b2-0abc-11e8-88c2-45d46e8befa2.png)
![img_0484](https://user-images.githubusercontent.com/7766387/35806995-59260b38-0abc-11e8-9eb1-42b445bdfe8c.PNG)

**Comment by taylorling** [comment] 2018-02-22 08:59
@gpeal Sorry for the follow up - should I file this as another issue, or this will not be fixed?

**Comment by gpeal** [comment] 2018-02-22 22:19
@taylorling This will not be fixed. The performance overhead would be too high. If you have ideas of efficient ways of solving it, let me know.

**Comment by miguelnserra** [comment] 2018-09-07 15:02
Same problem here. I usually use the pathfinder in Illustrator so separate the shapes or do it manually in After Effects.

**Comment by gpeal** [comment] 2019-09-03 14:39
@jeffsteinmetz @taylorling @miguelnserra  3.1.0 will have a new API `setApplyingOpacityToLayersEnabled` where you can manually enable this to render correctly. It isn't on by default because there is a performance overhead in doing so.

**Comment by miguelnserra** [comment] 2019-09-06 16:37
@gpeal Thanks!
