### ISSUE TITLE
Lottie animation was worse showed

### ISSUE THREAD

**Issue by ONVETI** [airbnb/lottie-android#2019] opened 2022-02-17 06:44 UTC
I have one json file but lottie animation don't show it. I don't know why it doesn't show.

Android Version: 11
Android Lottie Library: version 4.2.0

[Download json file](https://lottiefiles.com/download/private/zfubbay6)

* it's json file's apperance in json viewer
https://drawer.design/preview-lottie-animation/

![image](https://user-images.githubusercontent.com/70847827/154420004-e1493301-23ce-46c4-8b6e-c31b5426e233.png)

* it's json file's apperance in android application
![image](https://user-images.githubusercontent.com/70847827/154420142-0ae002d6-d2d2-44d8-a7ff-05ba786038f4.png)

**Comment by gpeal** [comment] 2022-02-21 05:54
Duplicate of #397

**Closed by gpeal** 2022-02-21 05:54 UTC
Labels: Rendering bug, Text
