### ISSUE TITLE
Android playback animation bug

### ISSUE THREAD

**Issue by Bovtriuk** [airbnb/lottie-android#494] opened 2017-10-11 09:01 UTC
Hello, there is a bug in Android version of lottie:

If you use an animated mask, either an animated trim path used as an alpha matte or an animated path mask. The playback duration in Lottie for Android will be just a fraction of what it should be. The same animation works fine both on website and on iOS, so bug presents only in Android version. 

The issue was found and tested on lottie library versions 2.0.0 and 2.2.5.

[Animated mask bug.zip](https://github.com/airbnb/lottie-android/files/1374885/Animated.mask.bug.zip)

**Comment by PavelSynek** [comment] 2017-10-18 12:57
Looks like you have the same problem as me in #478.

**Comment by gpeal** [comment] 2017-11-05 00:04
Correct, this is a duplicate of #478.

**Closed by gpeal** 2017-11-05 00:04 UTC
