### ISSUE TITLE
Caused by: com.airbnb.lottie.parser.moshi.JsonEncodingException:Use JsonReader.setLenient(true) to accept malformed JSON at path $

### ISSUE THREAD

**Issue by zhuangzhitu** [airbnb/lottie-android#1715] opened 2020-12-28 14:15 UTC
lottie version : 3.5.0...I can't reproduce it
crash trace:
com.airbnb.lottie.parser.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
java.lang.IllegalStateException:Unable to parse composition
com.airbnb.lottie.LottieAnimationView$1.a(SourceFile:78)
......
Caused by:
com.airbnb.lottie.parser.moshi.JsonEncodingException:Use JsonReader.setLenient(true) to accept malformed JSON at path $
com.airbnb.lottie.parser.moshi.JsonReader.a(SourceFile:249)
com.airbnb.lottie.parser.moshi.b.t(SourceFile:952)
com.airbnb.lottie.parser.moshi.b.o(SourceFile:348)
com.airbnb.lottie.parser.moshi.b.c(SourceFile:137)
com.airbnb.lottie.parser.t.a(SourceFile:57)
com.airbnb.lottie.e.a(SourceFile:390)
com.airbnb.lottie.e.a(SourceFile:383)
com.airbnb.lottie.e.a(SourceFile:313)
com.airbnb.lottie.e.b(SourceFile:306)
com.airbnb.lottie.e$6.a(SourceFile:296)
com.airbnb.lottie.e$6.call(SourceFile:293)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:929)

**Comment by gpeal** [comment] 2020-12-28 17:01
@zhuangzhitu Can you provide more information? Can you attach the json file? How are you loading it? What devices, etc?
Most likely, something within your app is causing it to load an invalid json file which it is then passing to Lottie.

**Comment by zhuangzhitu** [comment] 2020-12-29 02:03
> @zhuangzhitu Can you provide more information? Can you attach the json file? How are you loading it? What devices, etc?
> Most likely, something within your app is causing it to load an invalid json file which it is then passing to Lottie.
Model: HuaWei/EMOTION/EmotionUI_10. 0.0
At present, the occurrence probability of the production environment of crash is extremely low, so it seems that it is not certain to happen. A project dozens of JSON files, it is difficult to find out which problem, can exception inside, print this resource path.

**Comment by gpeal** [comment] 2020-12-29 03:34
@zhuangzhitu there really isn't anything that can be done without the json file and reproduction steps. I'm going to close this because it's not actionable as-is. If you are able to provide both, I'm happy to take a look though.

**Closed by gpeal** 2020-12-29 03:34 UTC
Labels: Rendering bug

**Comment by zhuangzhitu** [comment] 2020-12-29 03:49
> @zhuangzhitu there really isn't anything that can be done without the json file and reproduction steps. I'm going to close this because it's not actionable as-is. If you are able to provide both, I'm happy to take a look though.

thank you . But I think, at least throw out the wrong JSON file, and it will be hard to find the wrong JSON.

**Comment by zhuangzhitu** [comment] 2020-12-29 03:50
> > @zhuangzhitu there really isn't anything that can be done without the json file and reproduction steps. I'm going to close this because it's not actionable as-is. If you are able to provide both, I'm happy to take a look though.
> 
> thank you . But I think, at least throw out the wrong JSON file, and it will be hard to find the wrong JSON.

It's easy for you to know which JSON is causing the problem in your actual use. So far, it's probably a model fit problem

**Comment by zhuangzhitu** [comment] 2020-12-29 03:52
So now you get feedback that you don't know what JSON is causing the problem, and you close the problem. It's not necessary. @gpeal

**Comment by zhuangzhitu** [comment] 2021-05-26 08:09
HuaWei/EMOTION/EmotionUI_9.1.0 
FIG-AL10;Android 9,level 28
it can reproduct @gpeal

**Comment by chenkexu** [comment] 2021-06-29 02:52
我的项目也报这个错误，zip地址是：
[Airbnb.zip](https://github.com/airbnb/lottie-android/files/6730272/Airbnb.zip)

**Comment by surajsahani** [comment] 2021-07-27 15:44
I got the same issue. And it's  because of when someone tries to put HTTP URL in the place of instead of JSON_URL
`app:lottie_url="https://assets9.lottiefiles.com/packages/lf20_mcl3gvm9.json"`

**Comment by surajsahani** [comment] 2021-07-27 15:46
> I got the same issue. And it's because of when someone tries to put HTTP URL in the place of instead of JSON_URL
> `app:lottie_url="https://assets9.lottiefiles.com/packages/lf20_mcl3gvm9.json"`

for the beginners if we can suggest in documentation to put json url to raw than give url directory will that be any helpful? any thoughts.!! thank you

**Comment by nikossaperas** [comment] 2022-01-27 07:24
Had the same error after update on version 4.1.0.
Samsung Galaxy S9 - Android Version 10 
Reverted to version 3.0.1 and the issue was resolved.
Attaching the Json file causing the issue.

[lottie_animation.zip](https://github.com/airbnb/lottie-android/files/7948378/lottie_animation.zip)
.

**Comment by nikossaperas** [comment] 2022-04-19 07:35
I got rid of this error by verifying that the json file has no tabs, whitespaces - also making it a single line file.
Sharing just in case someone else has the same cause or error.
