### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by charleston10** [airbnb/lottie-android#342] opened 2017-06-16 18:58 UTC
Is there a solution to this problem? I researched issues, but I did not find :(
Are there any frame limitations?

Tks

**OutOfMemoryError**
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by java.lang.OutOfMemoryError
       at android.support.v4.view.animation.PathInterpolatorGingerbread.(Unknown Source)
       at android.support.v4.view.animation.PathInterpolatorGingerbread.(Unknown Source)
       at android.support.v4.view.animation.PathInterpolatorCompatBase.create(Unknown Source:46)
       at android.support.v4.view.animation.PathInterpolatorCompat.create(Unknown Source:83)
       at com.airbnb.lottie.Keyframe$Factory.newInstance(Unknown Source:134)
       at com.airbnb.lottie.Keyframe$Factory.parseKeyframes(Unknown Source:154)
       at com.airbnb.lottie.AnimatableValueParser.parseKeyframes(Unknown Source:40)
       at com.airbnb.lottie.AnimatableValueParser.parseJson(Unknown Source:31)
       at com.airbnb.lottie.AnimatableIntegerValue$Factory.newInstance(Unknown Source:40)
       at com.airbnb.lottie.AnimatableTransform$Factory.newInstance(Unknown Source:84)
       at com.airbnb.lottie.Layer$Factory.newInstance(Unknown Source:229)
       at com.airbnb.lottie.LottieComposition$Factory.parseLayers(Unknown Source:202)
       at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(Unknown Source:194)
       at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(Unknown Source:163)
       at com.airbnb.lottie.FileCompositionLoader.doInBackground(Unknown Source:17)
       at com.airbnb.lottie.FileCompositionLoader.doInBackground(Unknown Source:7)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by gpeal** [comment] 2017-06-20 16:21
@charleston10 how big is your animation? Would it be possible to send it to me?

**Comment by gpeal** [comment] 2017-06-29 02:38
@charleston10 also, in your animation, are you exporting every frame as a keyframe? If so, you can dramatically optimize the animation by using time interpolators between keyframes.

**Comment by gpeal** [comment] 2017-06-29 06:59
This is a duplicate of #39

**Closed by gpeal** 2017-06-29 06:59 UTC
