### ISSUE TITLE
`setMinAndMaxFrame` raise exception with correct values

### ISSUE THREAD

**Issue by Kevinrob** [airbnb/lottie-android#533] opened 2017-11-21 14:58 UTC
For reproducing the issue:
```
view.setMinAndMaxFrame(0, 11)
view.setMinAndMaxFrame(12, 30)
```
`UncaughtException: java.lang.IllegalArgumentException: Min value must be smaller then max value.`

Lottie `2.3.0`

This issue is because `setMinAndMaxFrame` will set min before setting max.

Workaround:
```
view.setMinAndMaxFrame(0, 11)
view.setMaxFrame(30)
view.setMinFrame(12)
```

**Comment by Tobias-Reich** [comment] 2017-11-23 15:06
I just raised the same issue. It got closed. But I found the same solution. Seems to work fine so far.

https://github.com/airbnb/lottie-android/issues/530

**Comment by gpeal** [comment] 2017-11-24 05:36
@Tobias-Reich It got closed because I fixed it on master :) I'll push a new release soon
Duplicate of https://github.com/airbnb/lottie-android/issues/530

**Closed by gpeal** 2017-11-24 05:36 UTC

**Comment by Kevinrob** [comment] 2017-11-24 05:56
Thank you!
