### ISSUE TITLE
Different version of android support library

### ISSUE THREAD

**Issue by IonutNegru87** [airbnb/lottie-android#473] opened 2017-09-20 09:13 UTC
My current project uses android support library `25.4.0`. 
After adding lottie to my module as an dependency (version **2.2.3**), it doesn't compile anymore failing at the manifest merger task due to multiple support library versions.

This is the error message:
```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.4.0] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:appcompat-v7:26.0.1] AndroidManifest.xml:28:13-35 value=(26.0.1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.
```

**Comment by gpeal** [comment] 2017-09-20 17:08
Duplicate of #77

**Closed by gpeal** 2017-09-20 17:08 UTC

**Comment by yaminijain** [comment] 2018-10-04 11:04
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.2'
            }
        }
    }
}
NOTE :Add this to your build.gradle and **make sure** you are using the same versions as '26.0.2'.
