### ISSUE TITLE
Help with understanding memory usage and Lottie visibility

### ISSUE THREAD

**Issue by derrickrc** [airbnb/lottie-android#1911] opened 2021-09-29 14:50 UTC
Hi, I am using older 5.1.1 Android devices and am getting the following exception after the app runs for some period: 

```
09-28 15:25:54.478 5479-5479/com.hoho.android.usbserial.examples.verde E/ActivityThread: Performing pause of activity that is not resumed: {com.hoho.android.usbserial.examples.verde/mypackage.CommunicateActivity}
    java.lang.RuntimeException: Performing pause of activity that is not resumed: {com.hoho.android.usbserial.examples.verde/mypackage.CommunicateActivity}
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3231)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3219)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3194)
        at android.app.ActivityThread.access$1000(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I am going to do additional testing today, but I have reason to believe this is memory related and caused by Lottie. The app is like a kiosk and the animations currently loop continuously. 

My question: I assume it will consume less memory if I set `lottie_loop=false`. If an animation is in fact looping and the visibility is being toggled based on user actions, does setting `visibility=gone` vs. `visibility=invisible` make a difference in terms of memory consumption? Or is it better to remove the view entirely each time (e.g., using `removeView()` and programmatically recreate the Lottie each time?  

Thank you!

**Comment by gpeal** [comment] 2021-09-30 03:32
@derrickrc It is highly unlikely that this is caused by Lottie. Regardless, Lottie doesn't use much memory once the animation is loaded so you should be able to loop without issue. Without more information or repro steps that indicate that this is due to Lottie, I'm going to have to close this.

**Closed by gpeal** 2021-09-30 03:32 UTC
Labels: Non-Rendering Bug

**Comment by derrickrc** [comment] 2021-09-30 14:55
Thanks @gpeal for responding so quickly. The thing is, I think this is Lottie related. As a test, overnight I ran two tablets side by side and had one where a MainActivity with 3 different Lotties where `lottie_loop=true` and the other with `false`. The one with `lottie_loop=true` crashed overnight with `Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 14310 (RenderThread)` (which is something I'd seen during my tests during the day as well). 

These are older Nexus 10 tablets running 5.1.1. Any ideas?

**Comment by Kingsavage3** [comment] 2021-09-30 20:07
No stop all

**Comment by derrickrc** [comment] 2021-09-30 20:23
@Kingsavage3 sorry what do you mean no stop all?

**Comment by gpeal** [comment] 2021-09-30 20:57
@derrickrc @Kingsavage3 probably subscribed to this thread and tried to unsubscribe via email...

That stack trace is independent of your first stack. When you turn the screen off, your activity should be stopped and Lottie should be paused. Can you put a breakpoint in cancelAnimation or pauseAnimation in LottieAnimationView and see if it triggers when you turn the screen off?

**Comment by derrickrc** [comment] 2021-09-30 20:59
Thanks @gpeal. I should have also shared, my app is a kiosk-type app and uses `wakeLock` so the screen is always on and the activity is always running. Does that likely change things?

**Comment by derrickrc** [comment] 2021-09-30 21:02
I should also share, I believe I've determined that the original exception I shared is not due to Lottie, but rather seems to be due to a combination of `FLAG_ACTIVITY_REORDER_TO_FRONT` and screen pinning causing this non-fatal minimizing behavior to happen intermittently. 

But the `Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 14310 (RenderThread)` I believe is caused by Lottie.

**Comment by gpeal** [comment] 2021-09-30 22:45
@derrickrc this could be a hardware specific issue. If you think that's the case. Try setting the render mode to software.

**Comment by derrickrc** [comment] 2021-10-06 04:59
@gpeal thanks Gabe. I actually already had that enabled -  any other tricks you have up your sleeve? If not, I think it's simply an issue due to it being an older Android tablet and I'll have to play around with the loop frequency to ensure it doesn't crash due to memory-related issues.

**Comment by gpeal** [comment] 2021-10-07 04:38
@derrickrc you shouldn't have to worry about manually managing any of Lottie's memory like that.
