### ISSUE TITLE
Text Alignment properties from After Effects are being ignored issue

### ISSUE THREAD

**Issue by krishnasajja** [airbnb/lottie-android#582] opened 2018-01-03 22:30 UTC
In the After Effects file, we are setting the Text Alignment to Center. When we replace the text dynamically with a bigger(or smaller) text, the text alignment seems to be set to left-aligned.

[Text.zip](https://github.com/airbnb/lottie-android/files/1601898/Text.zip)

**Comment by gpeal** [comment] 2018-01-16 07:02
Duplicate of #481

**Closed by gpeal** 2018-01-16 07:02 UTC
Labels: Text
