### ISSUE TITLE
can lottie support for identifying text line breaks

### ISSUE THREAD

**Issue by panzhi1** [airbnb/lottie-android#927] opened 2018-09-05 12:29 UTC
There are two lines of text in the ae text animation, but only one line is displayed on the lottie side, and the & character is not recognized.please tell me how to solve this problem?

**Comment by gpeal** [comment] 2018-09-05 12:59
Lottie's text support is *very* limited. Could you attach a failing animation for testing if support is added?

**Comment by panzhi1** [comment] 2018-09-06 01:17
[合成1.zip](https://github.com/airbnb/lottie-android/files/2355112/1.zip)
ok.

**Comment by martin-huang** [comment] 2018-09-29 08:35
why lottie doesn't use staticLayout to draw  two lines or more lines text ? ?  could you support it? thank you  very much

**Comment by gpeal** [comment] 2019-02-17 00:35
Duplicate of #401

**Closed by gpeal** 2019-02-17 00:35 UTC
Labels: Text
