### ISSUE TITLE
Animation not stop when LottieAnimationView become Invisible or Gone

### ISSUE THREAD

**Issue by weidongjian** [airbnb/lottie-android#376] opened 2017-07-11 07:35 UTC
I want to auto stop/pause animaitio when LottieAnimationView  is invisible...

**Comment by gpeal** [comment] 2017-07-12 22:18
@weidongjian It auto stops when it gets [detached from the window](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L239). Stopping when the visibility is invisible would not be the expected behavior.

**Comment by modydevelops** [comment] 2019-07-09 23:01
it is an expected behavior considering custom navigation solutions
-a user play's an animation and navigates to a different tab
-current tab get's GONE
-user click stop which is a shared btn between tabs
result: lottie malfunction and doesn't stop.

**Comment by gpeal** [comment] 2019-07-10 15:12
@modydevelops What version of Lottie?

**Comment by modydevelops** [comment] 2019-07-10 17:18
3.0.7

**Comment by gpeal** [comment] 2019-07-10 21:05
@modydevelops Can you create a sample project that reproduces this?

**Comment by modydevelops** [comment] 2019-07-10 21:35
I did a work around by (manually stopping all lottieAnimations then only play what's supposed to be played from sharedprefs) that's for each Container whenever it gets VISIBLE otherwise lottieAnimation restarts because it was playing when the visibility was GONE even if it got stopped while GONE. it's not the best thing for the performance but it solves my problem till further notice.Cheers

**Comment by gpeal** [comment] 2019-07-21 21:52
@modydevelops I'm going to close this for now but if you could attach a sample project that reproduces this, that would be great.

**Closed by gpeal** 2019-07-21 21:52 UTC
