### ISSUE TITLE
Suggestion: set hardware acceleration turned on by default, starting from certain API

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#718] opened 2018-04-08 16:23 UTC
According to my tests, it's safe to enable it from  Android L (API 21) .
But I think it's best to investigate it, to see from which it's the safest.

This is essential for smoother animations, as the default behavior currently is to have it disabled.

Just like on Android, where Google decided to have hardware acceleration optional till they decided it's stable and good enough, so they've set it enabled by default - so should it be here. 

If in most of the cases, animations will work better using hardware acceleration, I don't see why not enable it, and let developers disable it if they face issues.

**Comment by gpeal** [comment] 2018-04-09 16:27
Duplicate of #381

**Closed by gpeal** 2018-04-09 16:27 UTC
