### ISSUE TITLE
ANR:com.airbnb.lottie.utils.LottieValueAnimator.s 

### ISSUE THREAD

**Issue by YuTengfei** [airbnb/lottie-android#1649] opened 2020-10-14 05:36 UTC
this ANR issue happened on Android 6.0 only 
log:

(couldn't read /proc/self/task/18365/stack)
--
android.view.DisplayEventReceiver.nativeScheduleVsync(Native method:0)
android.view.DisplayEventReceiver.scheduleVsync(DisplayEventReceiver.java:134)
android.view.Choreographer.scheduleVsyncLocked(Choreographer.java:731)
android.view.Choreographer.scheduleFrameLocked(Choreographer.java:553)
android.view.Choreographer.postCallbackDelayedInternal(Choreographer.java:378)
- locked <0x0eeb8fad> (a java.lang.Object)
android.view.Choreographer.postFrameCallbackDelayed(Choreographer.java:455)
android.view.Choreographer.postFrameCallback(Choreographer.java:435)
com.airbnb.lottie.utils.LottieValueAnimator.s(unknown:3)
com.airbnb.lottie.utils.LottieValueAnimator.doFrame(unknown:1)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:882)
android.view.Choreographer.doCallbacks(Choreographer.java:696)
android.view.Choreographer.doFrame(Choreographer.java:628)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
android.os.Handler.handleCallback(Handler.java:743)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:150)
android.app.ActivityThread.main(ActivityThread.java:5621)
java.lang.reflect.Method.invoke!(Native method:0)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

need help to solve this problem

**Comment by gpeal** [comment] 2020-10-14 18:40
@YuTengfei Did this happen more than a single time? If it was just once, it is very possible that Android was being slow and this just happened to be where it got stuck but the root cause isn't in Lottie. This code hasn't changed in a long time and I haven't heard of any other reports of it causing ANRs.

**Comment by YuTengfei** [comment] 2020-10-15 06:02
> @YuTengfei Did this happen more than a single time? If it was just once, it is very possible that Android was being slow and this just happened to be where it got stuck but the root cause isn't in Lottie. This code hasn't changed in a long time and I haven't heard of any other reports of it causing ANRs.

@gpeal   yeah，It happened thousands of times in my APP，only on Android 6.0 devices

**Comment by gpeal** [comment] 2020-10-15 17:56
@YuriiTsap Can you reproduce it yourself?

**Comment by YuriiTsap** [comment] 2020-10-15 21:41
> @YuriiTsap Can you reproduce it yourself?

Well, this message was probably directed to @YuTengfei. If no, how I can be helpful with this one? :)
Seems to be a strange and non-trivial issue.
@YuTengfei exact steps to reproduce and more info on your device would be helpful.
I would agree with @gpeal - also looks for me as something that could be device-specific. Or appears due to system high load circumstances.

**Comment by Amon9527** [comment] 2020-10-16 06:30
I ran into the same problem, which appeared in the monkey test scenario, only on Android 6.0.1 devices.

**Comment by gpeal** [comment] 2020-10-24 20:39
@YuTengfei I'm not sure how to help with this one without a reliable reproduction. Lottie runs on millions of 6.0 devices every day and I haven't heard of any other reports of this.

**Comment by gpeal** [comment] 2020-12-25 22:57
In my tests, this function (which is just calling an Android platform API) only takes 0.05ms to 0.1ms. If this is ANRing, it is likely not Lottie's fault and represents a problem at the OS level. In that case, I would like to close this if there is nothing actionable on Lottie's side. Feel free to take another look yourself though.

**Closed** 2020-12-27 21:57 UTC
Labels: Help wanted
