### ISSUE TITLE
can not playAnimation in ListViewAdapter

### ISSUE THREAD

**Issue by fengjian123** [airbnb/lottie-android#1482] opened 2020-01-15 08:44 UTC
at version 3.3.1 ,I use LottieAnimationView to playAnimation in ListViewAdapter, but found it cannot play.Then I traced the source code and found that it is because in the latest version of playAnimation there is a condition that isShown() must be true, but in the items in listView, the isShown() of all views is false, so there is no method called

**Comment by DavidDTA** [comment] 2020-02-10 16:04
This may be the same issue as #1495

**Comment by gpeal** [comment] 2020-02-10 19:41
Duplicate of #1495

**Closed by gpeal** 2020-02-10 19:41 UTC
