### ISSUE TITLE
Compose crash: No virtual method setImageAssetManager

### ISSUE THREAD

**Issue by headsvk** [airbnb/lottie-android#1838] opened 2021-07-06 12:52 UTC
Repro commit for 1.0.0-beta09-1-SNAPSHOT:
https://github.com/headsvk/lottie-android/commit/ff2e2445d728f0bf2d1896a3b5bb45149f7ca0e3

Steps:
- Run issue-repro-commit app and it crashes instantly with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.lottie.issues.compose, PID: 23472
    java.lang.NoSuchMethodError: No virtual method setImageAssetManager(Lcom/airbnb/lottie/manager/ImageAssetManager;)V in class Lcom/airbnb/lottie/LottieDrawable; or its super classes (declaration of 'com.airbnb.lottie.LottieDrawable' appears in /data/app/~~D5JSKL9M3W6HokvkEzNL9A==/com.airbnb.lottie.issues.compose-o-MXvd1YM18tVOgSmcBuTA==/base.apk)
        at com.airbnb.lottie.ImageAssetDelegateSetterKt.setImageAssetManager(ImageAssetDelegateSetter.kt:10)
        at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$3.invoke(LottieAnimation.kt:120)
        at com.airbnb.lottie.compose.LottieAnimationKt$LottieAnimation$3.invoke(LottieAnimation.kt:106)
        at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:101)
```

Both Lottie Compose 1.0.0-beta07-1 and 1.0.0-beta09-1-SNAPSHOT started to crash today. I suspect the culprit is their dependency on Lottie Android 3.7.1-SNAPSHOT which makes non-snapshot Compose builds unstable. However, I couldn't reproduce it locally on master without getting the Lottie dependencies from repositories.

**Comment by thesauri** [comment] 2021-07-06 13:32
I encountered the very same problem today and I was also unable to reproduce it using the `issue-repro-compose` module.

I suspect that this may be due to the problem already being fixed in the Compose `1.0.0-rc01` snapshot that is already in master, but that seems to be failing in the CI pipeline. https://github.com/airbnb/lottie-android/runs/2995470801

**Comment by gpeal** [comment] 2021-07-06 18:42
Duplicate of #1837

**Closed** 2021-07-06 18:50 UTC
Labels: Non-Rendering Bug

**Comment by headsvk** [comment] 2021-07-07 09:37
I updated the repro branch to rc01 and it fixes the issue
