### ISSUE TITLE
NullPointerException occurs when using old format json

### ISSUE THREAD

**Issue by Forrest-Wangind** [airbnb/lottie-android#1369] opened 2019-08-28 10:32 UTC
when I using old-formated lottie, it's crashed as fellow, and my lottie version is 2.6.1, and sorry for that the json file is not allowed to attach

[loading_bear_android.json.txt](https://github.com/airbnb/lottie-android/files/3550352/loading_bear_android.json.txt)

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation com.airbnb.lottie.model.animatable.AnimatableFloatValue.createAnimation()' on a null object reference
        at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.<init>(TransformKeyframeAnimation.java:37)
        at com.airbnb.lottie.model.animatable.AnimatableTransform.createAnimation(AnimatableTransform.java:78)
        at com.airbnb.lottie.model.layer.BaseLayer.<init>(BaseLayer.java:102)
        at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:21)
        at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:45)
        at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
        at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:243)
        at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:205)
        at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:408)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:62)
        at com.airbnb.lottie.LottieAnimationView$1.onResult(LottieAnimationView.java:60)
        at com.airbnb.lottie.LottieTask.notifySuccessListeners(LottieTask.java:153)
        at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:26)
        at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:140)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6211)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
```

**Comment by gpeal** [comment] 2019-08-29 02:59
Duplicate of #1252

**Closed by gpeal** 2019-08-29 02:59 UTC
Labels: Rendering bug

**Comment by Forrest-Wangind** [comment] 2019-09-04 12:07
@gpeal our app have not been migrated to androidX which will bring a tremendous change, so what should I do without updating Lottie to 3.0+, only using old format JSON file?

**Comment by gpeal** [comment] 2019-09-05 00:15
@Forrest-Wangind There is a one-time `3.0.3-support`. I recommend migrating to androidx though.
