### ISSUE TITLE
please support PorterDuff ADD  MULTIPLY and so on

### ISSUE THREAD

**Issue by chongbo2013** [airbnb/lottie-android#1251] opened 2019-06-05 09:40 UTC
[lottie.zip](https://github.com/airbnb/lottie-android/files/3256531/lottie.zip)
I use the AE above to use the image for ADD operation, invalid effect

I know that android supports PorterDuff ADD request to implement the ADD mode of its picture.

**Comment by gpeal** [comment] 2019-06-10 16:05
@chongbo2013 Can you attach the AEP file?

**Comment by gpeal** [comment] 2019-06-10 16:09
I'm not sure I understand exactly what you are asking for. What is the after effects features you need?

**Comment by chongbo2013** [comment] 2019-06-24 08:04
> @ chongbo2013你可以附加AEP文件？

你好，aep文件在最上面  lottie.zip

**Comment by gpeal** [comment] 2019-06-24 16:14
@chongbo2013 Your aep didn't attach.

**Comment by chongbo2013** [comment] 2019-06-25 09:55
> @chongbo2013 Your aep didn't attach.
Excuse me, I thought I passed, I am making up now.
[Uploading 简化的端午 folder.zip…]()

**Comment by chongbo2013** [comment] 2019-06-25 09:57
[简化的端午 folder.zip](https://github.com/airbnb/lottie-android/files/3324685/folder.zip)

**Comment by gpeal** [comment] 2022-01-17 04:41
Duplicate of #1055

**Closed by gpeal** 2022-01-17 04:41 UTC
