### ISSUE TITLE
Animation do not shows properly

### ISSUE THREAD

**Issue by mohammadbahadori99** [airbnb/lottie-android#1476] opened 2020-01-08 08:34 UTC
Animation object don't rotate properly. for example check [this animation ](https://assets8.lottiefiles.com/packages/lf20_dhKO1k.json)
when i use this  in my android project, the fish shows up but it do not rotate and it move while it's fix.I'm using 3.3.1 version

**Comment by gpeal** [comment] 2020-02-16 02:40
Duplicate of #1401

**Closed by gpeal** 2020-02-16 02:40 UTC

**Comment by NiHang** [comment] 2020-10-26 07:26
I also encountered this problem, which version solved it?

**Comment by NahlaSaadAlDeen** [comment] 2022-11-16 07:49
Any ideas, please?
