### ISSUE TITLE
load more than ten animation lead OOM in Android 6.0.1,How to solve this problem

### ISSUE THREAD

**Issue by wuxianghua** [airbnb/lottie-android#1751] opened 2021-02-25 07:29 UTC
--logversion:utracea
Process Name: 'com.liquid.poros.pro'
Thread Name: 'main'
Back traces starts.
java.lang.OutOfMemoryError: Failed to allocate a 5516956 byte allocation with 440912 free bytes and 430KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:117)
	at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1067)
	at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:63)
	at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:33)
	at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:239)
	at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)

**Comment by ForLovelj** [comment] 2021-03-09 08:13
I found that Lottie did not properly reclaim native memory after exiting the page.
using multiple Image animations, the native memory will keep increasing, but the destroyed page memory will not be freed.
Are you experiencing the same phenomenon?

**Comment by gpeal** [comment] 2021-03-22 02:39
Duplicate of #1756

**Closed by gpeal** 2021-03-22 02:39 UTC
