### ISSUE TITLE
CompositionLayer is using Canvas#clipRect with invalid Region.Op on Android Pie

### ISSUE THREAD

**Issue by bmc08gt** [airbnb/lottie-android#925] opened 2018-09-04 16:43 UTC
Fatal Exception: java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
       at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
       at android.graphics.Canvas.clipRect(Canvas.java:826)
       at com.airbnb.lottie.CompositionLayer.drawLayer(CompositionLayer.java:91)
       at com.airbnb.lottie.BaseLayer.draw(BaseLayer.java:175)
       at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:305)

PR opened #923

**Comment by SeekerG95** [comment] 2018-09-04 19:37
I was having the same problem, but I was using a older version of the library, 2.0.0-rc1, when I updated to 2.6.0 I started to have the problem below:

java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Path$FillType.nativeInt' on a null object reference
at android.graphics.Path.setFillType(Path.java:268)
at com.airbnb.lottie.animation.content.GradientFillContent.<init>(GradientFillContent.java:62)
at com.airbnb.lottie.model.content.GradientFill.toContent(GradientFill.java:80)
at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:225)
at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:187)
at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:468)
at com.airbnb.lottie.LottieAnimationView$3.onCompositionLoaded(LottieAnimationView.java:411)
at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:29)
at com.airbnb.lottie.parser.AsyncCompositionLoader.onPostExecute(AsyncCompositionLoader.java:12)

**Comment by gpeal** [comment] 2018-09-05 02:00
@bmc08gt @SeekerG95 Can you attach crashing animations?

**Comment by SeekerG95** [comment] 2018-09-05 13:45
@gpeal the app crashes and restart before the animation is show in the screen.
Below i took a few screenshots, the problem seems to be in "fill.getFillType()" where "fillType" is null

airbnb/lottie/model/content/GradientFill.java
<img width="574" alt="image_03" src="https://user-images.githubusercontent.com/42980433/45096876-ecbcb180-b0f7-11e8-8994-a2ca1dc77529.png">

airbnb/lottie/animation/content/GradientFillContent.java
<img width="734" alt="image_01" src="https://user-images.githubusercontent.com/42980433/45096632-57b9b880-b0f7-11e8-844e-5421041ec821.png">

android/graphics/Path.Java
<img width="419" alt="image_02" src="https://user-images.githubusercontent.com/42980433/45096633-58524f00-b0f7-11e8-85dc-3316543df355.png">

**Comment by gpeal** [comment] 2018-09-05 15:05
@SeekerG95 Please attach an animation that repros this.

**Comment by SeekerG95** [comment] 2018-09-05 20:52
@gpeal you're talking about the json file of the animation, right? Unfortunately I wasn't authorized by my company to share files of the project, I know that this does not make your life easy to help us and I'm sorry for this. But i found the error and I will try my best to explain it.

In GradientFileParser.Java there is a static method called "parse", in this method there is a switch that sets fillType according to a "r" key in the "animation.json" file, the problem was that my "animation.json" did not had this key and fillType remained null, so i had to add it manually and then it started to work.

Before I changed to version 2.6.0 of lottie and API 28 of Android, it worked fine without the "r" key, my suggestion would be to set default values to these parameters. 

<img width="723" alt="screen shot 2018-09-05 at 17 41 20" src="https://user-images.githubusercontent.com/42980433/45119911-12b37780-b133-11e8-987e-4afabf85da6a.png">

**Comment by gpeal** [comment] 2018-09-06 18:06
@SeekerG95 Can you attach an aep file that reproduces this? It doesn't have to be the full animation. Delete all other layers and everything other than the gradient fill and a rectangle or some simple shape.

**Comment by gpeal** [comment] 2018-09-24 05:19
@SeekerG95 Are you exporting from After Effects with bodymovin? If you are, could you ask your designers to come up with a minimal-repro aep that reproduces this? You can send that over without sending your actual animation.

I'm going to close this for house keeping now but feel free to reopen if you can do this.

**Closed by gpeal** 2018-09-24 05:19 UTC

**Comment by huyaoqing1995** [comment] 2018-11-19 07:30
Hello, in CompositionLayer.java line 91，you can change "canvas.clipRect(originalClipRect, Region.Op.REPLACE);" to "if (Build.VERSION.SDK_INT >= 26) {
                    canvas.clipPath(mPath);
                } else {
                    canvas.clipPath(mPath, Region.Op.REPLACE);
                }
"
in Android P

**Comment by smborgesMobile** [comment] 2019-01-31 12:42
This issue is already fixed in V2.7.0.
Thank you so much.
