### ISSUE TITLE
Bug: while call LottieAnimationView.setMinAndMaxProgress in version 3.0.0 

### ISSUE THREAD

**Issue by 456838** [airbnb/lottie-android#540] opened 2017-11-27 08:36 UTC
Lottie version:3.0.0 
 when i call this function like this,it crash : 
```java
if (min > progress) {
            LogUtils.e("min1:" + min + ",progress1:" + progress);
            mMenuView.setMinAndMaxProgress(LottieUtil.convertProgress(progress), LottieUtil.convertProgress(min));
            mMenuView.playAnimation();
        } else {
            LogUtils.e("min2:" + LottieUtil.convertProgress(min) + ",progress2:" + LottieUtil.convertProgress(progress));   //convertProgress  method convert int to float
            
            mMenuView.setMinAndMaxProgress(LottieUtil.convertProgress(progress), LottieUtil.convertProgress(min));
            mMenuView.reverseAnimationSpeed();
            mMenuView.playAnimation();

        }
```
ps: i guess the max var did not clear 

![](https://i.imgur.com/nvvD7dy.png)

![](https://i.imgur.com/dYasXwT.png)

**Comment by gpeal** [comment] 2017-11-28 22:17
duplicate of #533

**Closed by gpeal** 2017-11-28 22:17 UTC
