### ISSUE TITLE
Track matte (alpha) not working on Android

### ISSUE THREAD

**Issue by dzolnai** [airbnb/lottie-android#1899] opened 2021-09-13 08:43 UTC
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).

Alpha matte seems to be a supported feature on Android

2. I know what part of my animation doesn't work.

Bottom clipping, see bug description for more details

3. I have created a simplified version of my animation

The animation is quite simple
 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

[Rating Lottie Issue.aep.zip](https://github.com/airbnb/lottie-android/files/7152815/Rating.Lottie.Issue.aep.zip)

**Describe the bug**
The animation should have a round mask at the bottom, which is also visible in LottieFiles preview on web: https://lottiefiles.com/76538-thumbs-up-masked
But when we try the Android export, the bottom is not clipped anymore:
[thumbs_up_keyframes.json.zip](https://github.com/airbnb/lottie-android/files/7152787/thumbs_up_keyframes.json.zip)

**What version of Lottie did you test this on?**
3.4.2 and 4.1.0

**What version of Android did you test this on?**
Android 11

**Steps To Reproduce**

Play the animation.
You can also open it in the LottieFiles / Lottie app from the play store, it has the same issue

**Screenshots**

![Screen Shot 2021-09-13 at 10 43 27](https://user-images.githubusercontent.com/3629582/133052686-52fb7674-3d9a-4e9d-8a1c-e11cf48f502f.png)

**Comment by gpeal** [comment] 2022-01-17 05:21
Your animation uses rounded corners which were recently added for the 5.0 release!
Duplicate of #106

**Closed by gpeal** 2022-01-17 05:21 UTC
Labels: Rendering bug
