### ISSUE TITLE
3D rotate problem

### ISSUE THREAD

**Issue by yangfeng1994** [airbnb/lottie-android#1486] opened 2020-01-17 07:19 UTC
**Read this or your issue will be closed**
in android 3D Animation not executed
[归档.zip](https://github.com/airbnb/lottie-android/files/4075494/default.zip)

* Before opening a new issue, look through existing issues for duplicates.
* Simplify your animation to the simplest animation that reproduces your issue.
* Zip your After Effects AEP file and attach it. Your issue will be auto-closed if it doesn't have an AEP or no explicit reason otherwise is given.
* If you don't know English, run your issue through Google Translate.
* If you leave the template text in your issue, it will be closed.

**Comment by gpeal** [comment] 2020-01-17 20:36
Duplicate of #1415

**Closed by gpeal** 2020-01-17 20:36 UTC
