### ISSUE TITLE
Interact with elements from animation

### ISSUE THREAD

**Issue by fweigl** [airbnb/lottie-android#595] opened 2018-01-15 16:06 UTC
Hi, is there a possibility or feature planned to interact with certain elements in an animation?
For instance, find a "button" (as a shape in the animation, not a native button) via some sort of ID and set an Android onClickListener to it?

**Comment by gpeal** [comment] 2018-01-15 20:51
@fweigl Yes, I plan to add support for this in the future but it doesn't support it yet.

**Comment by gpeal** [comment] 2018-02-12 07:34
Duplicate of #444

**Closed by gpeal** 2018-02-12 07:34 UTC
Labels: New feature
