### ISSUE TITLE
playAnimation doesn't work correctly in recyclerView / bindViewHolder

### ISSUE THREAD

**Issue by matheusbrandao** [airbnb/lottie-android#1742] opened 2021-02-09 19:37 UTC
As you can see in my gif, the first time I open the screen containing a recyclerView, the animation occurs normally.

However, if I click on an action and execute `` playAnimation () ``, the animation seems to be lost, not running correctly from its beginning to the end.

Any idea???

![Peek 09-02-2021 16-34](https://user-images.githubusercontent.com/19668094/107418054-f92d6b80-6af4-11eb-9209-e3e02b3c0f40.gif)

**Comment by matheusbrandao** [comment] 2021-02-09 20:12
Doing some tests, I found that it may be linked to changes in the database (and when I click the button it changes a value in the database).

In addition I am using the flow, which may be causing the card to be reloaded and my animation does not perform correctly.

**Comment by gpeal** [comment] 2021-02-10 17:39
@matheusbrandao is this a duplicate of https://github.com/airbnb/lottie-android/issues/1324?

**Comment by matheusbrandao** [comment] 2021-02-23 17:20
No @gpeal , it is another case. 

I resolved my problem waiting for the end of the animation. In that case, when the action ends, I perform my action.

**Closed** 2021-03-22 02:52 UTC
Labels: Rendering bug

**Comment by zhtoo** [comment] 2022-06-25 06:55
> @matheusbrandao[这是#1324](https://github.com/airbnb/lottie-android/issues/1324)的副本吗？

I have the same problem. 'playAnimation()' doesn't work. It‘s ok when I call 'v.post(v.playAnimation )'. Maybe it's because I called 'recyclerview.setItemAnimator(null)' to resolve item flicker caused by 'notifyitemchanged". I think 'recyclerview.setItemAnimator(null)' will disable the animation of the item.
