### ISSUE TITLE
Use json animation to report an error

### ISSUE THREAD

**Issue by xlp-shawn** [airbnb/lottie-android#1323] opened 2019-07-16 10:54 UTC
Process: com.example.mac.annotiondemo, PID: 23330
    java.lang.IllegalStateException: Missing values for keyframe.
        at com.airbnb.lottie.animation.keyframe.FloatKeyframeAnimation.getValue(FloatKeyframeAnimation.java:16)
        at com.airbnb.lottie.animation.keyframe.FloatKeyframeAnimation.getValue(FloatKeyframeAnimation.java:8)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getValue(BaseKeyframeAnimation.java:125)
        at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.getMatrix(TransformKeyframeAnimation.java:113)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:186)
        at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
        at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:188)
        at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:311)
        at android.widget.ImageView.onDraw(ImageView.java:1353)

The version I am using is 2.5.4. The way to use it is the easiest to use json in the layout. please to help me see what is wrong with me, thank you.
[animate_lock.json.zip](https://github.com/airbnb/lottie-android/files/3396730/animate_lock.json.zip)

**Comment by xlp-shawn** [comment] 2019-07-16 10:58
I can play json normally on the website, but it can't play normally on android.
https://lottiefiles.com/share/AEpSkM

**Comment by gpeal** [comment] 2019-07-19 02:50
Duplicate of #1177

**Closed by gpeal** 2019-07-19 02:50 UTC
