### ISSUE TITLE
 NetworkCache isTemp usage error

### ISSUE THREAD

**Issue by JoinGitLiu** [airbnb/lottie-android#1277] opened 2019-06-21 10:29 UTC
When I downloaded the json file with **NetworkFetcher.fetchSync**(Context context, String url) I found that the file could be written to the cache, but the cache file could not be read. The reason is that **NetworkCache's 131 line isTemp** is reversed and should be 
` ( ! isTemp ? extension.tempExtension(): extension.extension)`

**Comment by gpeal** [comment] 2019-06-23 02:54
Duplicate of #1114. I also recommend upgrading Lottie.

**Closed by gpeal** 2019-06-23 02:54 UTC
