### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference

### ISSUE THREAD

**Issue by daniel0x7CC** [airbnb/lottie-android#904] opened 2018-08-23 00:58 UTC
```
 val transAnimation = ObjectAnimator.ofFloat(animationdog, "translationX", 0f, windowManager.defaultDisplay.width.toFloat())
        transAnimation.duration = 3000//set duration
        transAnimation.start()//start animation
        transAnimation.addListener(object : Animator.AnimatorListener {
            override fun onAnimationRepeat(animation: Animator?) {
            }

            override fun onAnimationEnd(animation: Animator?) {
                animationdog.pauseAnimation()
                val intent = Intent(this@SplashActivity, JoinActivity::class.java)
                startActivity(intent)
                overridePendingTransition(R.anim.fade_in, R.anim.fade_out)
                finish()
            }

            override fun onAnimationCancel(animation: Animator?) {
            }

            override fun onAnimationStart(animation: Animator?) {
            }

        })
```
Keep in mind that: **animationdog** is the lottieview
I am getting an error on lottie when I start a new Intent:

 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.recycle()' on a null object reference
        at com.airbnb.lottie.b.b.a(ImageAssetManager.java:125)
        at com.airbnb.lottie.f.c(LottieDrawable.java:185)
        at com.airbnb.lottie.LottieAnimationView.a(LottieAnimationView.java:270)

Hope someone can help, thanks.

**Comment by gpeal** [comment] 2018-08-24 17:16
Duplicate of #586

**Closed by gpeal** 2018-08-24 17:16 UTC
