### ISSUE TITLE
Make LottieComposition properties getters public

### ISSUE THREAD

**Issue by xgear-public** [airbnb/lottie-android#133] opened 2017-02-20 15:42 UTC
I think it would be convenient to have public access to LottieComposition properties getters:
```
  Rect getBounds() {
    return bounds;
  }

  long getDuration() {
    return duration;
  }

  long getEndFrame() {
    return endFrame;
  }

  int getFrameRate() {
    return frameRate;
  }

  List<Layer> getLayers() {
    return layers;
  }

  long getStartFrame() {
    return startFrame;
  }

  boolean hasMasks() {
    return hasMasks;
  }

  boolean hasMattes() {
    return hasMattes;
  }

  float getScale() {
    return scale;
  }
```

**Comment by gpeal** [comment] 2017-02-20 20:04
This is a dupe of #93.

It'll be fixed this week. Sorry for the inconvenience.

**Closed by gpeal** 2017-02-20 20:04 UTC

**Comment by gpeal** [comment] 2017-02-20 20:06
@xgear-public Just out of curiosity, why do you need these?

**Comment by xgear-public** [comment] 2017-02-21 10:31
I need to know width vs height ratio to calculate proper size of LottieAnimationView to make animation fullscreen width on all devices (as i described in #112 ). Also it would be good to know if animation contain Masks or Mattes (for example if i load animation dynamically and need to take some actions in case if its has Masks or Mattes and it's affects performance).

**Comment by xgear-public** [comment] 2017-02-21 10:32
Anyway thank you for such a fantastic lib!

**Comment by gpeal** [comment] 2017-02-22 05:57
@xgear-public 1.5.0 is out!

**Comment by BlingBling43** [comment] 2023-11-28 00:45
> I think it would be convenient to have public access to LottieComposition properties getters:
> ```
>   Rect getBounds() {
>     return bounds;
>   }
> 
>   long getDuration() {
>     return duration;
>   }
> 
>   long getEndFrame() {
>     return endFrame;
>   }
> 
>   int getFrameRate() {
>     return frameRate;
>   }
> 
>   List<Layer> getLayers() {
>     return layers;
>   }
> 
>   long getStartFrame() {
>     return startFrame;
>   }
> 
>   boolean hasMasks() {
>     return hasMasks;
>   }
> 
>   boolean hasMattes() {
>     return hasMattes;
>   }
> 
>   float getScale() {
>     return scale;
>   }
> ```

- - [ ]__
