### ISSUE TITLE
ArraySet NoClassDefFoundError on v2.1.0

### ISSUE THREAD

**Issue by hexrelib** [airbnb/lottie-android#389] opened 2017-07-18 09:24 UTC
I have a json file from my team's designer, it works fine when I used version 2.0.0, but after I upgraded to version 2.1.0, my app crashed. Here is the exception:

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArraySet;
	at com.airbnb.lottie.PerformanceTracker.(PerformanceTracker.java:22)
	at com.airbnb.lottie.LottieComposition.(LottieComposition.java:44)
	at com.airbnb.lottie.LottieComposition.(LottieComposition.java:33)
	at com.airbnb.lottie.LottieComposition$Factory.fromJsonSync(LottieComposition.java:260)
	at com.airbnb.lottie.LottieComposition$Factory.fromInputStream(LottieComposition.java:226)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:17)
	at com.airbnb.lottie.FileCompositionLoader.doInBackground(FileCompositionLoader.java:7)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by gpeal** [comment] 2017-07-18 14:16
@hexrelib have you excluded the dependency on the support lib in your gradle file or something?

**Comment by hexrelib** [comment] 2017-07-19 01:58
@gpeal yes, I use "compile(libs.lottie) { exclude group: 'com.android.support' }" in my gradle file to solve dependencies conflicts.

**Comment by gpeal** [comment] 2017-07-19 03:33
@hexrelib Well that'll do it... Why do you need to exclude the entire support lib. Something definitely sounds wrong with that setup. It's also not lottie specific.

**Comment by gpeal** [comment] 2017-07-20 02:08
I'm going to close this. You can't use Lottie without the support lib.

**Closed by gpeal** 2017-07-20 02:08 UTC

**Comment by DanielKaparunakis** [comment] 2017-07-20 20:23
@gpeal I can reproduce this issue as well. My project needs to use the support library v23 so to solve dependency conflicts I did the following in my `build.gradle` file:
```
...
compile ('com.airbnb.android:lottie:2.1.0') {
        exclude group: 'com.android.support'
}
compile 'com.android.support:appcompat-v7:23.4.0'
...
```
Per issue #77. Also as @hexrelib points out, it seems like the issue is only with v2.1.0. I tried v2.0.0, v1.5.3 and v1.5.2 and I did not have issues there.

**Comment by gpeal** [comment] 2017-07-21 03:15
@DanielKaparunakis It's because I added code that uses ArraySet in 2.1 which I guess was added in a support library after 23. Why, may I ask, do you need to compile with support lib 23? There are very few good reasons to need to do that...

**Comment by DanielKaparunakis** [comment] 2017-07-21 14:31
As in turns out, I had the relationship of compileSdkVersion, minSdkVersion and targetSdkVersion mixed up in my head. I've cleared up my confusion so I am now using the latest support library.

**Comment by gpeal** [comment] 2017-07-21 17:09
@DanielKaparunakis yup, that was my assumption :) Glad you got it figured out.

**Comment by hyne-shan** [comment] 2017-09-23 08:17
you can modify PerformanceTracker.java

private final Set<FrameListener> frameListeners = initSet();

private Set<FrameListener> initSet(){
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          return new ArraySet<>();
      }else {
          return new HashSet<>();
      }
  }

**Comment by Kyson** [comment] 2017-10-26 05:46
i got same problem
my support v4 version is 25.0.0, in this version,there is no arrayset class found,maybe it has been deprecated.
so it is better to use **android.util.ArraySet** instead of android/support/v4/util/ArraySet

thx.

**Comment by Kyson** [comment] 2017-10-26 06:18
sorry , my mistake.
the problem's reason is :
there is no arrayset in support v4 version of 25.0.0 ,but it can be found in 25.3.1.
so just upgrade support v4 version to 25.3.1 and it is ok now.

**Comment by zhaoqianglulu** [comment] 2018-08-23 06:14
这个问题在后面的2.5.5版本上有修改吗？目前使用还是会报错上述错误啊

**Comment by ashwindmk** [comment] 2018-12-09 06:55
I am using androidx, hence I need to exclude support group. Still getting the error.
