### ISSUE TITLE
LottieSample crash

### ISSUE THREAD

**Issue by petma** [airbnb/lottie-android#1109] opened 2019-02-11 01:02 UTC
I clicked "Dynamic properties",then crashed, I used genymotion's android 9.0 to test the app
 
  java.lang.IndexOutOfBoundsException: Index: -1
        at java.util.Collections$EmptyList.get(Collections.java:4502)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.getCurrentKeyframe(BaseKeyframeAnimation.java:86)
        at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:56)
        at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:451)
        at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:117)
        at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:129)
        at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:105)
        at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:88)
        at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:155)
        at com.airbnb.lottie.LottieDrawable.setFrame(LottieDrawable.java:555)
        at com.airbnb.lottie.LottieDrawable.setProgress(LottieDrawable.java:574)
        at com.airbnb.lottie.LottieDrawable.addValueCallback(LottieDrawable.java:793)
        at com.airbnb.lottie.LottieAnimationView.addValueCallback(LottieAnimationView.java:663)
        at com.airbnb.lottie.samples.DynamicActivity.setupValueCallbacks(DynamicActivity.kt:59)
        at com.airbnb.lottie.samples.DynamicActivity.access$setupValueCallbacks(DynamicActivity.kt:19)
        at com.airbnb.lottie.samples.DynamicActivity$onCreate$5.run(DynamicActivity.kt:53)

**Comment by gpeal** [comment] 2019-02-11 05:24
Duplicate of #1078

**Closed by gpeal** 2019-02-11 05:24 UTC
