### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Teviz** [airbnb/lottie-android#497] opened 2017-10-12 07:16 UTC
Hello everyone.
When I using lottie 2.2.0, I found in `KeyFrame.Factory#newInstance` method, invoke `pathInterpolatorCache.get(hash)` sometimes may throw an ArrayIndexOutOfBoundsException. 
It's hard to reproduce but exists exactly. 
Here are log and json.

Caused by java.lang.ArrayIndexOutOfBoundsException
  | java.lang.System.arraycopy (System.java)
  | android.support.v4.util.SparseArrayCompat.put (SparseArrayCompat.java:209)
  | com.airbnb.lottie.Keyframe$Factory.newInstance (Keyframe.java:160)
  | com.airbnb.lottie.Keyframe$Factory.parseKeyframes (Keyframe.java:181)
  | com.airbnb.lottie.AnimatableValueParser.parseKeyframes (AnimatableValueParser.java:40)
  | com.airbnb.lottie.AnimatableValueParser.parseJson (AnimatableValueParser.java:31)
  | com.airbnb.lottie.AnimatableIntegerValue$Factory.newInstance (AnimatableIntegerValue.java:44)
  | com.airbnb.lottie.AnimatableTransform$Factory.newInstance (AnimatableTransform.java:133)
  | com.airbnb.lottie.Layer$Factory.newInstance (Layer.java:258)
  | com.airbnb.lottie.LottieComposition$Factory.parsePrecomps (LottieComposition.java:312)
  | com.airbnb.lottie.LottieComposition$Factory.fromJsonSync (LottieComposition.java:264)
  | com.airbnb.lottie.LottieComposition$Factory.fromInputStream (LottieComposition.java:226)
  | com.airbnb.lottie.FileCompositionLoader.doInBackground (FileCompositionLoader.java:17)
  | com.airbnb.lottie.FileCompositionLoader.doInBackground (FileCompositionLoader.java:7)
  | android.os.AsyncTask$2.call (AsyncTask.java:288)
  | java.lang.Thread.run (Thread.java:831)
[json.zip](https://github.com/airbnb/lottie-android/files/1378400/json.zip)

So I think maybe it's better to check the index before getting the `interpolatorRef`. After all, the potential runtime exception will cause an app crash which takes the bad user experience.
Thanks.

**Comment by gpeal** [comment] 2017-10-18 04:08
Duplicate of #472

**Closed by gpeal** 2017-10-18 04:08 UTC
