### ISSUE TITLE
Animation on android looks inconsistence with web

### ISSUE THREAD

**Issue by dokiKit** [airbnb/lottie-android#973] opened 2018-10-10 03:04 UTC
I used aep from https://pixelbuddha.net/freebie/free-animated-flat-emojis-aep to output json file. 

Previewing it on lottiefiles is fine, but when I test it on android lottie preview app I find out that all the path seems surrounded by a white margin. What may caused it? It shows no warning though on the app.

https://www.lottiefiles.com/share/NVRz8j

**Comment by gpeal** [comment] 2018-11-22 17:47
Duplicate of #1004. Delete the stroke around the eyes for now.

**Closed by gpeal** 2018-11-22 17:47 UTC
