### ISSUE TITLE
Lottie Animation Tracing All at Once Instead of Step by Step in Jetpack Compose

### ISSUE THREAD

**Issue by NuggetMcPollo** [airbnb/lottie-android#2402] opened 2023-10-25 19:15 UTC
Describe the bug

I’m trying to use a Lottie animation in my Android app with Jetpack Compose. The animation is a hiragana trace that is supposed to be traced step by step. However, when I play the animation in my app, it gets traced all at once. This is different from how the animation plays in the preview on the Lottie website.

What version of Lottie did you test this on?

Lottie:    implementation ("com.airbnb.android:lottie-compose:6.1.0")
Jetpack Compose 1.8.0

Steps To Reproduce
1. Download the Lottie animation from the official Lottie website.
2. Add the animation to the Android app using Jetpack Compose.
3. Play the animation.
4. Observe that the animation gets traced all at once instead of step by step.

This is a fragment of my code to display the animation:

@Composable
fun LottieKana(
    lottie: String,
) {
    val fullLottieUrl = Constants.BASE_URL + lottie
    
     var enabled by remember { mutableStateOf(false) }

    LaunchedEffect(key1 = true){
            enabled = true
        }

    val composition by rememberLottieComposition(LottieCompositionSpec.Url(fullLottieUrl))
    val progress by animateLottieCompositionAsState(
        composition = composition,
        isPlaying = enabled,
        iterations = LottieConstants.IterateForever,
    )
    
    Column(
        modifier = Modifier.fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Box(modifier = Modifier.fillMaxWidth()) {
            LottieAnimation(
                modifier = Modifier
                    .size(sizeLottie)
                    .align(Alignment.Center)
                    .clickable(
                        interactionSource = interactionSource,
                        indication = null
                    ) {
                        if (!buttonVisible) {
                            buttonVisible = true
                            enabled = false
                        }
                    },
                composition = composition,
                progress = { if (enabled) progress else 1f }
            )
         }
     }
}

https://github.com/airbnb/lottie-android/assets/119012808/bb1207ae-b6bc-454e-9a9e-b2a0ed5125dd

**Comment by gpeal** [comment] 2023-11-14 21:34
Duplicate of #2262

**Closed by gpeal** 2023-11-14 21:34 UTC
Labels: Non-Rendering Bug
