### ISSUE TITLE
Stuck with weird speed bouncing animation behaviors on different devices. more info inside

### ISSUE THREAD

**Issue by rosconabn** [airbnb/lottie-android#649] opened 2018-02-24 14:57 UTC
Hello, 
 as stated in the title I'm seeing different behaviors while playing the same file.
I'm testing this on an old kind phone LG4 and on a new one S8+.

The problem is simple when I play the animation on the LG4 (very slow phone) it actually plays smoothly.
On the other device instead (S8+) I see the animation going like is bouncing back few frames and then moving forward. 

I don't think there is nothing strange with my animation because I also tried with the testing animations on github website. 
I tried to enable or disable hardware acceleration and nothing change.
Also the disk chace strategy is set to strong , same no changes.
I have no onUpdate listeners.
I only run 3 different animations at the same time.
I'm using it as popup menu button with 2 more options coming from the back of the main menu button.
After 600 milliseconds it should pause.
 (also there is another problem that the timing is never the same on the exact frame but I understand why and I kind solved that).

            Handler handler = new Handler();
            handler.postDelayed(()-> {
                    btn_t.pauseAnimation();
                    btn_minus.pauseAnimation();
                    btn_plus.pauseAnimation();
                    btn_plus.setClickable(true);
                    btn_minus.setClickable(true);
            }, 600);
            playTBtns();

Now Do you have any idea why is behaving like that ?

**Comment by gpeal** [comment] 2018-02-25 07:34
@rosconabn Can you attach the animation? It'll be hard to reproduce this without it.

**Comment by rosconabn** [comment] 2018-02-25 20:41
As I said before just try to run any animation with an S8+ and let me know if you see the same animation issues.

**Comment by gpeal** [comment] 2018-02-25 23:12
It looks fine on my S8. Can you attach a video?

**Comment by rosconabn** [comment] 2018-02-26 11:53
I will add a video but can you also confirm that you are compiling with 
    compileSdkVersion 27
    buildToolsVersion '27.0.2'

    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:multidex:1.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.android.support:customtabs:27.0.2'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:cardview-v7:27.0.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'

**Comment by rosconabn** [comment] 2018-02-26 12:03
Can you add an email where to send you the videos since I don't feel comfortable adding these videos here. Thank you

**Comment by rosconabn** [comment] 2018-02-26 12:32
A small update, I just tried with the     compile 'com.airbnb.android:lottie:2.5.0-rc1' because I heard from someone in the forum that something was different and surprisingly it magically works with that.
So there is something that didn't get in  2.5.0 ? or got removed ? 
meanwhile I will use the 2.5.0-rc1

**Comment by gpeal** [comment] 2018-02-27 00:34
@rosconabn lottie a_t airbnb.com

It is likely related to https://github.com/airbnb/lottie-android/pull/624

**Comment by rosconabn** [comment] 2018-03-01 09:33
So are you pushing a new build for it or what?

**Comment by gpeal** [comment] 2018-03-01 16:14
No, you never sent a video and I don't know what the issue is.

**Comment by gpeal** [comment] 2018-03-02 04:13
I'm going to assume this is a duplicate of #657

**Closed by gpeal** 2018-03-02 04:13 UTC

**Comment by rosconabn** [comment] 2018-03-02 14:31
Oh I'm glad you can read and then assume what's the issue.
