### ISSUE TITLE
Animation broken when loading the screen from background

### ISSUE THREAD

**Issue by rddsantos** [airbnb/lottie-android#1781] opened 2021-04-05 13:08 UTC
Hello guys, I’m having a problem with a Lottie animation when the screen goes into background and comes back in and I was wondering if someone could help me out.

**Describe the bug**
When the screen is opened for the first time, the animation plays as expected but when the screen goes into background
and then comes back in, the animation is broken. It still plays, but the visuals are completely wrong.

**What version of Lottie did you test this on?**
3.6.1

**What version of Android did you test this on?**
11

**Steps To Reproduce**
Open the screen, check that the animation is playing as expected. 
Go to the next screen, so that the current goes into the stopped state. Go back to the initial 
screen and the animation is broken.

**Additional info**

<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

.
.
.

<com.airbnb.lottie.LottieAnimationView
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/imgAsset"
        app:lottie_autoPlay="true"
        app:lottie_fileName="lottie/gaming_module_winner_bg.json"
        app:lottie_loop="true" />

</androidx.constraintlayout.widget.ConstraintLayout>

Please note: I’m not doing any changes to the view programmatically and the asset is inside src/main/assets/lottie.

What have I tried to solve this? 
-> Fifferent scaletypes, different scales and also sizes of the LottieAnimationView.
-> Tested the animation on the Lottie Sample app. It gives me 0 warnings and plays as excepted, i.e. before the screen
going into background.
-> Different lottie versions.
-> Debugged lottie code but everything seems to be ok so I really have no clue on why this is hapening.

**Screenshots**
https://user-images.githubusercontent.com/17315406/113576476-e5e3db80-961f-11eb-8642-8f6352a2489f.mp4

**Comment by gpeal** [comment] 2021-04-06 03:28
@rddsantos Can you attach your animation?

**Comment by rddsantos** [comment] 2021-04-06 07:21
Surething, here it is:

[gaming_module_winner_bg.json.zip](https://github.com/airbnb/lottie-android/files/6262824/gaming_module_winner_bg.json.zip)

**Comment by rddsantos** [comment] 2021-04-08 08:13
Hey @gpeal any news on this?

**Comment by gpeal** [comment] 2021-04-18 02:52
@rddsantos Hmm, this might be specific to your app. It seems to be working fine for me:

https://user-images.githubusercontent.com/1307745/115132585-66a6be00-9fb6-11eb-8301-bb587b02d0c3.mp4

I'm going to close this as likely not an issue with lottie itself. However, if you are able to reproduce this in a sample project, feel free to reopen this with the project.

**Closed by gpeal** 2021-04-18 02:52 UTC
Labels: Rendering bug

**Comment by rddsantos** [comment] 2021-04-20 15:09
Heyy @gpeal, I managed to solve the problem by disabling LottieAnimationView saved state
