### ISSUE TITLE
Bug: sample app doesn't handle correct direction of text, in "Animated text" 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#707] opened 2018-03-26 17:32 UTC
I get this when writing in Hebrew :

![image](https://user-images.githubusercontent.com/5357526/37922291-d79f3efa-3134-11e8-9359-3d14ec5592ed.png)

**Comment by gpeal** [comment] 2018-03-27 01:49
Lotte doesn't support RTL. Text support is pretty basic for now and it may be quite a while before RTL is supported unless someone does a PR for it

**Comment by AndroidDeveloperLB** [comment] 2018-03-27 05:17
@gpeal Can you please set it as a feature request then?

**Comment by ArthurVimond** [comment] 2019-03-06 08:07
@gpeal Hi! I'm currently working on this feature, and I have a few questions:

1- Should we detect the direction for each TextLayer input and draw them independently or just getting the device current language setting and apply the same direction for all texts?

2- Regarding the text justification, drawing RTL texts with Justification.LEFT_ALIGN should start from the right (not from the left), right? Also, should we refactor the Justification enums as START_ALIGN, CENTER, END_ALIGN (like layout margin / padding system)?

Thanks.

**Comment by AndroidDeveloperLB** [comment] 2019-03-06 08:23
@ArthurVimond What you wrote doesn't belong here... Please make a new thread about it.

**Comment by gpeal** [comment] 2019-08-11 01:03
Duplicate of #1145

**Closed by gpeal** 2019-08-11 01:03 UTC
Labels: New feature, Text

**Comment by AndroidDeveloperLB** [comment] 2019-08-11 05:14
Ummm.... Why mark a request from "Mar 26, 2018" as duplicate of one from "Mar 6" of this year (2019) ?
