### ISSUE TITLE
Is there a safe version to enable hardware acceleration ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie-android#682] opened 2018-03-14 10:29 UTC
I've tried now on an old device (Nexus 4) with Android Kitkat, and the sample app (from the Play Store) crashes on the "Animation Viewer" screen.
When I create a POC app, which shows an Lottie animation, enabling hardware acceleration hides the animation completely.

I use this:

        animation_view.useHardwareAcceleration(true)

I've also tried this:

        animation_view.enableMergePathsForKitKatAndAbove(true)

But I don't think it does anything noticeable on the animation file we work on.

And in XML, it is as such:

```
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" tools:context=".MainActivity">

    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view" android:layout_width="0dp" android:layout_height="0dp"
        android:scaleType="centerCrop" app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" app:lottie_autoPlay="true" app:lottie_loop="true"
        app:lottie_rawRes="@raw/data"/>

...
```
When running on other devices, with newer Android versions, it works fine.

Is there a safe version of Android that I should turn hardware acceleration on?
Or maybe it's already enabled by default, starting from certain Android version?

**Comment by AndroidDeveloperLB** [comment] 2018-03-14 12:04
According to my tests on the few various devices and Android versions I have, I think it's safe to use hardware-acceleration starting from Android L (API 21).

**Comment by gpeal** [comment] 2018-03-14 17:08
Duplicate of #381 
@AndroidDeveloperLB there are two problems: 
1) Not everything is supported (like dash path effects): https://developer.android.com/guide/topics/graphics/hardware-accel.html
2) [It isn't always faster ](https://developer.android.com/guide/topics/graphics/hardware-accel.html)

**Closed by gpeal** 2018-03-14 17:08 UTC

**Comment by AndroidDeveloperLB** [comment] 2018-03-14 17:34
@gpeal How is it duplicate?
I ask from which version is it safe to use it, so that I could add a check to enable it when it's ok.
He asks for auto-enabling it.
In my case, I need it to run as smooth as possible, because it's intended to be used as a progress animation, while the app does something in the background, which might be "heavy".

**Comment by gpeal** [comment] 2018-03-14 22:52
@AndroidDeveloperLB Sorry, the second link didn't paste correctly.
I have some docs explaining it in more detail here: http://airbnb.io/lottie/android/performance.html#hardware-acceleration

**Comment by AndroidDeveloperLB** [comment] 2018-03-15 06:29
I've already read this.
And it's incorrect. API 19 is not safe to enable it, as I've written.
On API 19, enabling HA could result in not showing the animation.
Not only that, but running the sample from the Play Store crashes for some reason on API 19, when reaching the viewer.

**Comment by gpeal** [comment] 2018-03-15 06:35
@AndroidDeveloperLB What is the stack trace for the KitKat crash?

Sorry, I'd like to help out with the ResourceSet issue but I can't repro it and the internet doesn't leave many clues. If other people start having this problem, I'll spend more time investigating though. Do try clearing your global gradle caches. I'm not sure what the path on Windows is.

**Comment by gpeal** [comment] 2018-03-15 06:36
@AndroidDeveloperLB What is the stack trace for the KitKat crash?

The safety depends on your animation and the api version.

**Comment by AndroidDeveloperLB** [comment] 2018-03-15 07:57
Can you please investigate the animation on API 19 though? I can send the file to you if you wish via email, but just keep it privately since it's of the office. 
I've looked at it further, and the animation does get shown, but only a tiny part of it compared to without HA. 

Have you tried to run the sample from the Play Store, on emulator with Android 4.4, and tried the viewer ?
It crashes right there.
I don't think it's related though, but I just wanted to try other animations with HA. 
About the stack trace of the crash from the Play Store, I've already sent a report. You should see it in the Play Console. Here it is :

```
03-15 09:47:15.356 30824-30824/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.airbnb.lottie, PID: 30824
    android.view.InflateException: Binary XML file line #104: Error inflating class TextView
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at com.airbnb.lottie.samples.TypeExtensionsKt.inflate(TypeExtensions.kt:28)
        at com.airbnb.lottie.samples.AnimationFragment.onCreateView(AnimationFragment.kt:85)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_warning_wrapped.xml from drawable resource ID #0x7f07007a
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
        at android.widget.TextView.<init>(TextView.java:806)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at com.airbnb.lottie.samples.TypeExtensionsKt.inflate(TypeExtensions.kt:28) 
        at com.airbnb.lottie.samples.AnimationFragment.onCreateView(AnimationFragment.kt:85) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_warning.xml from drawable resource ID #0x7f070079
        at android.content.res.Resources.loadDrawable(Resources.java:2096)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:159)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2092)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
        at android.widget.TextView.<init>(TextView.java:806) 
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76) 
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72) 
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103) 
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016) 
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at com.airbnb.lottie.samples.TypeExtensionsKt.inflate(TypeExtensions.kt:28) 
        at com.airbnb.lottie.samples.AnimationFragment.onCreateView(AnimationFragment.kt:85) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2092)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:159) 
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937) 
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877) 
        at android.content.res.Resources.loadDrawable(Resources.java:2092) 
        at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
        at android.widget.TextView.<init>(TextView.java:806) 
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:76) 
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72) 
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103) 
        at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016) 
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at com.airbnb.lottie.samples.TypeExtensionsKt.inflate(TypeExtensions.kt:28) 
        at com.airbnb.lottie.samples.AnimationFragment.onCreateView(AnimationFragment.kt:85) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5001) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
        at dalvik.system.NativeStart.main(Native Method) 

```

**Comment by AndroidDeveloperLB** [comment] 2018-03-15 08:30
I've succeeded importing the repository and ran it on Android 4.4.
Seems it fails to show various animations correctly when HA is enabled.
See attached video file.

[device-2018-03-15-102936.zip](https://github.com/airbnb/lottie-android/files/1814517/device-2018-03-15-102936.zip)

So you don't need to use the file I have. It occurs even on the sample of the repository.

**Comment by AndroidDeveloperLB** [comment] 2018-03-15 09:02
When using HA, it can even crash on Android 4.4  on the sample of the repository.
Just try the one called "MailSent", and enable HA.

**Comment by gpeal** [comment] 2018-03-15 16:02
@AndroidDeveloperLB That crash is fixed on master. I'm almost done with an entirely new sample app and it works on KitKat. I also tried mailsent on KitKat and it worked. Can you attach the stack trace?
You can also email animations to lottie [at] airbnb.com

**Comment by AndroidDeveloperLB** [comment] 2018-03-15 18:56
@gpeal You tried on the version of the sample that I didn't?
I will try again on Sunday.

**Comment by gpeal** [comment] 2018-03-15 19:56
@AndroidDeveloperLB Yes, the sample app on master on the repo is a totally new app :)

**Comment by AndroidDeveloperLB** [comment] 2018-03-15 20:15
I mean not just the one from the Play Store. I mean one that here on the repository. Was it updated recently?

**Comment by gpeal** [comment] 2018-03-16 15:01
Yes.

**Comment by AndroidDeveloperLB** [comment] 2018-03-16 15:36
Oh ok.

**Comment by AndroidDeveloperLB** [comment] 2018-03-18 08:05
I've now wanted to try it out, but 2.5.1 is still the latest version.
So I've cloned the repository instead, and tried the sample.
I've ran it on both emulator and Nexus 4 (with Android 4.4). 
On the emulator, the "mailsent" sample works fine even if I enable HA.
On the Nexus 4, however, it crashes.
Also, the "Lottie Logo 1" sample doesn't show well on the Nexus 4 when I enable HA.
Attached video to show these issues.
[device-2018-03-18-100258.zip](https://github.com/airbnb/lottie-android/files/1822470/device-2018-03-18-100258.zip)

The only error/warning logs I see that are related, are those:

```
03-18 10:03:58.217 7471-7503/com.airbnb.lottie W/LOTTIE: Lottie doesn't support 3D layers.
03-18 10:04:06.195 7471-7471/com.airbnb.lottie A/libc: Fatal signal 11 (SIGSEGV) at 0x00000005 (code=1), thread 7471 (m.airbnb.lottie)
03-18 10:04:06.646 598-7737/? W/ActivityManager: Process com.airbnb.lottie has crashed too many times: killing!
      Force finishing activity com.airbnb.lottie/.samples.PlayerActivity
03-18 10:04:06.646 598-7737/? W/ActivityManager:   Force finishing activity com.airbnb.lottie/.samples.MainActivity
03-18 10:04:06.676 598-868/? W/InputDispatcher: channel '4292fd68 com.airbnb.lottie/com.airbnb.lottie.samples.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-18 10:04:06.676 598-868/? E/InputDispatcher: channel '4292fd68 com.airbnb.lottie/com.airbnb.lottie.samples.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-18 10:04:06.676 598-868/? W/InputDispatcher: channel '429dd6d8 com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-18 10:04:06.676 598-868/? E/InputDispatcher: channel '429dd6d8 com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

BTW, you can remove the `buildToolsVersion` in all gradle files. This is used automatically.

**Comment by gpeal** [comment] 2018-03-19 01:33
@AndroidDeveloperLB One of my other hesitations about automatically recommending hardware acceleration is that it could be theoretically supported on any device but actually broken on certain devices. I've had strange device specific issues in the past. Facebook doesn't use hardware acceleration for their reactions for exactly this reason.

What is the stack trace when it crashes? If you see that dialog, there has to be one in logcat.

**Comment by AndroidDeveloperLB** [comment] 2018-03-19 09:06
@gpeal I've already sent you the logs. Didn't you see them?

Here it is again, from the time of launching the app, to the time it crashes. The filtering is by warning level :

```
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 63: Landroid/app/Activity;.finishAfterTransition ()V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 67: Landroid/app/Activity;.getReferrer ()Landroid/net/Uri;
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 73: Landroid/app/Activity;.postponeEnterTransition ()V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 75: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
    Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (942)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
03-19 11:05:28.147 12477-12477/com.airbnb.lottie E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback23Impl', referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve new-instance 562 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;) in Landroid/support/v4/app/ActivityCompat;
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 76: Landroid/app/Activity;.setEnterSharedElementCallback (Landroid/app/SharedElementCallback;)V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
03-19 11:05:28.147 12477-12477/com.airbnb.lottie E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback21Impl', referenced from method android.support.v4.app.ActivityCompat.setEnterSharedElementCallback
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve new-instance 561 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;) in Landroid/support/v4/app/ActivityCompat;
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 76: Landroid/app/Activity;.setEnterSharedElementCallback (Landroid/app/SharedElementCallback;)V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
    Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (942)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
03-19 11:05:28.147 12477-12477/com.airbnb.lottie E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback23Impl', referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve new-instance 562 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;) in Landroid/support/v4/app/ActivityCompat;
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 77: Landroid/app/Activity;.setExitSharedElementCallback (Landroid/app/SharedElementCallback;)V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
03-19 11:05:28.147 12477-12477/com.airbnb.lottie E/dalvikvm: Could not find class 'android.support.v4.app.ActivityCompat$SharedElementCallback21Impl', referenced from method android.support.v4.app.ActivityCompat.setExitSharedElementCallback
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve new-instance 561 (Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;) in Landroid/support/v4/app/ActivityCompat;
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 77: Landroid/app/Activity;.setExitSharedElementCallback (Landroid/app/SharedElementCallback;)V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 78: Landroid/app/Activity;.shouldShowRequestPermissionRationale (Ljava/lang/String;)Z
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: VFY: unable to resolve virtual method 83: Landroid/app/Activity;.startPostponedEnterTransition ()V
03-19 11:05:28.147 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
    Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (942)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
03-19 11:05:28.157 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
03-19 11:05:28.157 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
    Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl; (942)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback23Impl;' failed
03-19 11:05:28.157 12477-12477/com.airbnb.lottie W/dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl; (52)
    Link of class 'Landroid/support/v4/app/ActivityCompat$SharedElementCallback21Impl;' failed
03-19 11:05:28.798 12477-12477/com.airbnb.lottie W/dalvikvm: method Landroid/support/v7/widget/DropDownListView;.lookForSelectablePosition incorrectly overrides package-private method with same name in Landroid/widget/ListView;
03-19 11:05:29.178 12477-12503/com.airbnb.lottie W/LOTTIE: Lottie doesn't support 3D layers.
03-19 11:05:38.068 12477-12477/com.airbnb.lottie A/libc: Fatal signal 11 (SIGSEGV) at 0x00000005 (code=1), thread 12477 (m.airbnb.lottie)
03-19 11:05:38.618 598-12715/? W/ActivityManager: Process com.airbnb.lottie has crashed too many times: killing!
      Force finishing activity com.airbnb.lottie/.samples.PlayerActivity
03-19 11:05:38.628 598-12715/? W/ActivityManager:   Force finishing activity com.airbnb.lottie/.samples.MainActivity
03-19 11:05:38.648 598-868/? W/InputDispatcher: channel '42b30540 com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-19 11:05:38.648 598-868/? E/InputDispatcher: channel '42b30540 com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-19 11:05:38.648 598-868/? W/InputDispatcher: channel '430effc8 com.airbnb.lottie/com.airbnb.lottie.samples.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-19 11:05:38.648 598-868/? E/InputDispatcher: channel '430effc8 com.airbnb.lottie/com.airbnb.lottie.samples.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-19 11:05:38.648 598-3264/? W/InputDispatcher: Attempted to unregister already unregistered input channel '42b30540 com.airbnb.lottie/com.airbnb.lottie.samples.PlayerActivity (server)'
03-19 11:05:38.658 598-1188/? W/InputDispatcher: Attempted to unregister already unregistered input channel '430effc8 com.airbnb.lottie/com.airbnb.lottie.samples.MainActivity (server)'
03-19 11:05:38.718 1047-5017/? W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.NullPointerException
        at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
        at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
03-19 11:05:38.718 598-3115/? W/InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 12477 uid 10341

```

**Comment by vivek-modi** [comment] 2019-09-27 23:23
does any one know how to use setEnterSharedElementCallback in lottie..

**Comment by vivek-modi** [comment] 2019-09-27 23:24
i am trying to implement but its not showing in next activity
