### ISSUE TITLE
StackOverflowError when setting setMinFrame using AnimatorListener AnimationEnd 

### ISSUE THREAD

**Issue by everloser** [airbnb/lottie-android#1667] opened 2020-11-05 09:17 UTC
Android 10 (SDK 29)

Redmi Note 8 Pro
Huawei 荣耀 8X
Huawei HUAWEI nova 5T
Redmi Note 9

code:
with(binding.lottieAnimationStart) {
            setAnimation("new_start.json")
            repeatCount = 0
            addAnimatorListener(object : Animator.AnimatorListener {
                override fun onAnimationStart(animator: Animator) = Unit
                override fun onAnimationRepeat(animator: Animator) = Unit
                override fun onAnimationCancel(animator: Animator) = Unit
                override fun onAnimationEnd(animator: Animator) {
                    repeatCount = LottieDrawable.INFINITE
                    repeatMode = LottieDrawable.RESTART
                    setMinFrame(44)
                    playAnimation()
                }
            })
            playAnimation()
        }

java.lang.StackOverflowError: 
  at com.airbnb.lottie.utils.LottieValueAnimator.setMinAndMaxFrames (LottieValueAnimator.java:174)
  at com.airbnb.lottie.utils.LottieValueAnimator.setMinFrame (LottieValueAnimator.java:163)
  at com.airbnb.lottie.LottieDrawable.setMinFrame (LottieDrawable.java:476)
  at com.airbnb.lottie.LottieAnimationView.setMinFrame (LottieAnimationView.java:600)
  at ... Fragment$onViewCreated$1$1.onAnimationEnd
  at android.animation.Animator$AnimatorListener.onAnimationEnd (Animator.java:554)
  at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd (BaseLottieAnimator.java:73)
  at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation (LottieValueAnimator.java:217)
  at com.airbnb.lottie.LottieDrawable.playAnimation (LottieDrawable.java:428)
  at com.airbnb.lottie.LottieAnimationView.playAnimation (LottieAnimationView.java:574)
  at ... Fragment$onViewCreated$1$1.onAnimationEnd
  at android.animation.Animator$AnimatorListener.onAnimationEnd (Animator.java:554)
  at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd (BaseLottieAnimator.java:73)
  at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation (LottieValueAnimator.java:217)
  at com.airbnb.lottie.LottieDrawable.playAnimation (LottieDrawable.java:428)
  at com.airbnb.lottie.LottieAnimationView.playAnimation (LottieAnimationView.java:574)

**Comment by gpeal** [comment] 2020-11-05 16:31
Duplicate of #1534 

Explanation here
https://github.com/airbnb/lottie-android/issues/1534#issuecomment-720537189

**Closed by gpeal** 2020-11-05 16:31 UTC
