### ISSUE TITLE
how to clear LottieCompositionCache

### ISSUE THREAD

**Issue by youxiachai** [airbnb/lottie-android#1343] opened 2019-08-06 08:06 UTC
I find LottieCompositionCache have clear method ,but it restrict to library, can't call this method.

because LottieComposition.images have many bitmap, I want to clear it when other page not use lottie anim.

Can add new api use this method?

**Comment by gpeal** [comment] 2019-08-06 23:50
Duplicate of #1289

**Closed by gpeal** 2019-08-06 23:50 UTC
Labels: New feature

**Comment by kartik1225** [comment] 2019-08-17 11:04
`LottieCompositionCache` Can you make this class public?
I want to use `evictAll()` LRUcahe.
Basically, I want to forcefully re-render Lottie animation (without using Lottie cache)

**Comment by gpeal** [comment] 2019-08-17 18:33
@kartik1225 What do you mean by re-render? Exposing that function won't do that.

**Comment by kartik1225** [comment] 2019-08-17 19:14
@gpeal I am trying to do this [#1233](https://github.com/airbnb/lottie-android/issues/1233#issuecomment-496150571) but text font is not changing after the animation is cached.
Basically, I want to clear the `LottieCompositionCache` so I can change the font of the animation after the animation is loaded.

**Comment by kartik1225** [comment] 2019-08-21 19:40
@gpeal  Will this resolve the font changing problem?

**Comment by joharhussain** [comment] 2019-10-29 10:31
I am using animation file from RAW folder with language specifier i.e. en,it,ar etc. When I switch app language from application it does not load localize resources because of caching. After restarting application it works fine. Need to clear lottie cache.

**Comment by gpeal** [comment] 2019-10-29 19:52
@joharhussain #1289 is still open
