### ISSUE TITLE
BaseLottieAnimator.java line 87

### ISSUE THREAD

**Issue by PankajS24** [airbnb/lottie-android#1356] opened 2019-08-12 04:37 UTC
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM
       at java.util.concurrent.CopyOnWriteArrayList.iterator + 188(CopyOnWriteArrayList.java:188)
       at java.util.concurrent.CopyOnWriteArraySet.iterator + 361(CopyOnWriteArraySet.java:361)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate + 87(BaseLottieAnimator.java:87)
       at com.airbnb.lottie.utils.LottieValueAnimator.doFrame + 96(LottieValueAnimator.java:96)
       at android.view.Choreographer$CallbackRecord.run + 957(Choreographer.java:957)
       at android.view.Choreographer.doCallbacks + 734(Choreographer.java:734)
       at android.view.Choreographer.doFrame + 667(Choreographer.java:667)
       at android.view.Choreographer$FrameDisplayEventReceiver.run + 945(Choreographer.java:945)
       at android.os.Handler.handleCallback + 751(Handler.java:751)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6776(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1518(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main + 1408(ZygoteInit.java:1408)

**Comment by gpeal** [comment] 2019-08-12 16:52
Duplicate of #1357

**Closed by gpeal** 2019-08-12 16:52 UTC
Labels: Non-Rendering Bug
