### ISSUE TITLE
Issue on S7 edge

### ISSUE THREAD

**Issue by chengzheustc** [airbnb/lottie-android#230] opened 2017-03-28 12:28 UTC
hi，the path is not well on Samsung Galaxy S7 edge while it performs well on the other devices.
Thanks for your time!

<img width="436" alt="qq20170328-202935 2x" src="https://cloud.githubusercontent.com/assets/4488715/24404838/52b083c8-13f5-11e7-8369-a3951cf261ae.png">
[like.aep.zip](https://github.com/airbnb/lottie-android/files/875612/like.aep.zip)

**Comment by gpeal** [comment] 2017-03-30 16:07
Hmm, this doesn't happen on my flat S7. I'll try and get my hands on an S7 edge.
Just as a test, can you make sure that each vertex has control points (which appear as handles in After Effects). Maybe you have some points with handles then a vertex that's just a point.

**Comment by gpeal** [comment] 2017-04-08 19:20
@chengyin I just tried all of the compositions in your AE file on an S7 edge and they all looked fine. Can you try again on master. It's going to be tough to fix this one unless I can repro it.

**Comment by mradzinski** [comment] 2017-04-10 19:13
@gpeal Just tested this on my S7 Edge and couldn't reproduce it either, but as per the screenshot he's using beta3, so it might have been fixed in beta4 😕

**Comment by gpeal** [comment] 2017-04-19 11:57
@chengzheustc Feel free to reopen this if you can still repro it.

**Closed by gpeal** 2017-04-19 11:57 UTC

**Comment by chengzheustc** [comment] 2017-04-21 01:17
@gpeal thanks for your time. I will try again.

**Comment by chengzheustc** [comment] 2017-04-21 01:27
@gpeal , I pull the latest code. it performs well on S7 edge now. Thanks
