### ISSUE TITLE
Animation playback on Android displays delayed timing

### ISSUE THREAD

**Issue by ision-industries** [airbnb/lottie-android#1642] opened 2020-10-06 21:35 UTC
I am dealing with a peculiar issue that I have no idea what could be the cause. I have project that contains a lot of shape layers that are parented to one layer. The shape layers themselves have animated key frames as well as the main parented layer. 

The animation seemed to render correctly as the animation plays correctly on the web and mobile browsers (as you can see when you test the animation link). The issue arises when I test the animation in the LottieFiles Android app where playback displays one layer has delayed timing and it is very noticeable. 

Here is a screenshot of the delayed layer.
![image](https://user-images.githubusercontent.com/58711145/95262130-91d77600-07f9-11eb-8d57-9c2c720dc2d4.jpeg)

Here is a screenshot of how the animation is supposed to look without the delay ![image](https://user-images.githubusercontent.com/58711145/95262225-b6335280-07f9-11eb-9e35-f1567612f20b.jpeg)

Here is the [animation link](https:lottiefiles.com/share/xgzvwqpj) so you can test it

Here is the [After Effects project](https://drive.google.com/file/d/1eyj8HJDRPGHfz224Hzc_5KGdJGYRmRFl/view?usp=drivesdk) file

**Comment by Mahmoood** [comment] 2020-10-09 04:44
I also have the same issue on Android and iOS for a particular lottie file.
It works on the web.
Still trying to figure out the cause of that issue.

**Comment by Mahmoood** [comment] 2020-10-09 11:25
I figured out that inside the Lottie file I was using time remapping tech such as loopOut('pingpong') which is not supported in Android & iOS.

**Comment by ision-industries** [comment] 2020-10-10 01:31
I also figured out the issue. The antenna and antenna dot are synced up. The keyframes for both layers are aligned to animate at the same time. The problem was that the keyframes easing values were slightly mismatched on one layer. The slight mismatched values were no problem playing the animation on the web. But for some reason Android and iOS has a hard time playing the animation. So my issue is fixed but I am still curious to know why a slight keyframe ease value difference would cause such a noticeable delay.

**Comment by ision-industries** [comment] 2020-10-10 01:35
> I figured out that inside the Lottie file I was using time remapping tech such as loopOut('pingpong') which is not supported in Android & iOS.
> 
> 
> 
> 

Expressions are not supported on mobile. But time remap is supported but not on windows. I also ran into another issue with time remapping keyframe with no expressions but that I need to figure out

**Comment by gpeal** [comment] 2020-10-24 20:40
I'm going to close this because it looks like it was using expressions (loopOut).
@ision-industries If you have another time remapping issue, please open a separate issue and attach a sample animation.

**Closed by gpeal** 2020-10-24 20:40 UTC
