### ISSUE TITLE
A Lottie file does not render Text specified with a Google font in Jetpack Compose

### ISSUE THREAD

**Issue by afaktor** [airbnb/lottie-android#2209] opened 2022-12-12 20:33 UTC
**Checklist**

1. My animation doesn't use any [unsupported features](http://airbnb.io/lottie/#/supported-features).
2. I know what part of my animation doesn't work.
3. I have created a simplified version of my animation 
4. I have attached the AEP file (as a zip file so it can be attached) that only has the part of the animation that doesn't work.

**Describe the bug**

**What version of Lottie did you test this on?**

**What version of Android did you test this on?**

**Steps To Reproduce**

**Screenshots**

**Comment by gpeal** [comment] 2022-12-13 01:50
Duplicate of #2119

**Closed by gpeal** 2022-12-13 01:50 UTC
Labels: Rendering bug
