### ISSUE TITLE
Support Gradient fills

### ISSUE THREAD

**Issue by subtleGradient** [airbnb/lottie-android#47] opened 2017-02-02 21:36 UTC

**Comment by gpeal** [comment] 2017-02-02 22:10
👍  This is on our roadmap :)

**Comment by bearprada** [comment] 2017-02-17 01:06
do you have a document to describe the roadmap for this awesome project? @gpeal

**Comment by gpeal** [comment] 2017-02-17 02:33
@bearprada I'll add one to the readme :) Many feature requests are tracked in issues though and I'll try to tag them to releases when possible.

Some precomp support and polystar support as well as a few other things are coming soon!

**Comment by podrivo** [comment] 2017-03-15 17:55
Really hoping to have this feature as soon as possible! (:

**Comment by gpeal** [comment] 2017-03-17 07:26
@subtleGradient @dong108 @podrivo @wingjay @rkim-homma @martinbonnin @bearprada 

Please give linear gradients a try with 2.0.0-beta1 :)

I'll leave this open until I finish radial gradients.

**Comment by podrivo** [comment] 2017-03-24 18:28
@gpeal Radial gradient didn't work for me.

Here's a ZIP with .aep and .json: [Archive.zip](https://github.com/airbnb/lottie-android/files/868826/Archive.zip)

What I got:
![radial](https://cloud.githubusercontent.com/assets/546221/24308363/73abf474-10a6-11e7-8db3-04f3204dde18.png)


Expected:
![screen shot 2017-03-24 at 3 25 51 pm](https://cloud.githubusercontent.com/assets/546221/24308292/30a32652-10a6-11e7-9df0-625400ef89c0.png)

**Comment by gpeal** [comment] 2017-03-24 18:59
@podrivo this will be fixed in beta3 which I'm about to push

**Comment by podrivo** [comment] 2017-03-26 16:06
@gpeal Gradient is working in beta3, but it's being applied related to the canvas and not to the element. So in my example, it feels like a mask.

**Comment by gpeal** [comment] 2017-03-26 16:08
Can you attach the aep file?

**Comment by podrivo** [comment] 2017-03-26 16:10
@gpeal It's the same as above.
Here it is: [Archive.zip](https://github.com/airbnb/lottie-android/files/868826/Archive.zip)

**Comment by gpeal** [comment] 2017-03-27 18:09
@podrivo I'm not sure I understand what the issue is. This is what it looks like for me now:
![image](https://cloud.githubusercontent.com/assets/1307745/24370879/d71d7684-12dd-11e7-93fb-3560521a18f6.png)
Is there a difference between this and the expected one?

**Comment by podrivo** [comment] 2017-03-27 20:08
I'm scaling the gradient applied element.

In AE, everything is scaled, including the gradient, but in Lottie, just the form is scaled and not the gradient, so the element behaves as a mask.

In AE:
![screen shot 2017-03-27 at 4 48 19 pm](https://cloud.githubusercontent.com/assets/546221/24375708/a91cf5e8-130f-11e7-856c-5f9266926b2f.png)

In Lottie:
![screen shot 2017-03-27 at 5 06 24 pm](https://cloud.githubusercontent.com/assets/546221/24375729/be0548de-130f-11e7-90e6-a60075a019f0.png)

**Comment by gpeal** [comment] 2017-03-27 20:17
Ah, I see. Thanks

**Closed** 2017-05-09 15:54 UTC
Labels: enhancement
