### ISSUE TITLE
lottie on android is not consistent 

### ISSUE THREAD

**Issue by thomasponzo** [airbnb/lottie-android#1335] opened 2019-07-24 15:27 UTC
I dont know what I am doing wrong here but the same animation with the same resolution is working on my emulator but on my phone it doesn't https://lottiefiles.com/share/e5dPWJ . it cuts the t of and why I dont know! http://prntscr.com/ojhc7h

**Comment by gpeal** [comment] 2019-07-31 23:54
Duplicate of #1334

**Closed by gpeal** 2019-07-31 23:54 UTC
Labels: Rendering bug
