### ISSUE TITLE
Lottie animation is paused when setScale is called

### ISSUE THREAD

**Issue by Luosoha** [airbnb/lottie-android#1759] opened 2021-03-11 08:54 UTC
**Describe the bug**

I am making a draggable and zoomable LottieAnimationView. So I want to zoom the view when user touch the screen with two fingers, the problem is that when I call the method **setScale** in LottieAnimationView, the animation is paused and only after I finish zooming the view that the animation is resumed.

```java
@Override
    public void unscheduleDrawable(Drawable who) {
        if (!ignoreUnschedule && who == lottieDrawable && lottieDrawable.isAnimating()) {
            **pauseAnimation();**  <<<<<<<<<<<<<<< This one
        } else if (!ignoreUnschedule && who instanceof LottieDrawable && ((LottieDrawable) who).isAnimating()) {
            ((LottieDrawable) who).pauseAnimation();
        }
        super.unscheduleDrawable(who);
    }
```

```java
private void setLottieDrawable() {
        boolean wasAnimating = isAnimating();
        // Set the drawable to null first because the underlying LottieDrawable's intrinsic bounds can change
        // if the composition changes.
        setImageDrawable(null);
        setImageDrawable(lottieDrawable);
        if (wasAnimating) {
            // This is necessary because lottieDrawable will get unscheduled and canceled when the drawable is set to null.
            **lottieDrawable.resumeAnimation();** <<<<<<<<<<<<<<< And this one
        }
    }
```

I tried to comment these 2 lines in LottieAnimationView.java and it did work fine after that (I can add another flag to bypass these calls for my specific situation) . But I wonder if there will be any other problems that may happen because of that.

I am more than happy to accept other workarounds as well.
Thanks!

**Comment by gpeal** [comment] 2021-03-22 02:35
@Luosoha I see what the issue is here. When you change the scale via `setScale`, Lottie re-sets the drawable because it causes its intrinsic size to change. I would recommend one of two workarounds:
1) Try using just Android `setScaleX` and `setScaleY`. If that works, it'll be more efficient because it likely won't lead to a re-draw either.
2) Try using [dynamic properties](http://airbnb.io/lottie/#/android?id=dynamic-properties) to change the TRANSFORM_SCALE of the root layer of your animation.

**Comment by gpeal** [comment] 2021-03-22 02:35
For this particular issue, I'm not sure how to work around it because the actual drawable is unscheduled and rescheduled and Lottie doesn't know that it will be rescheduled when it is unscheduled.

**Comment by gpeal** [comment] 2021-03-22 02:53
I'm going to close this for now but I hope one of these two workarounds works for you.

**Comment by Luosoha** [comment] 2021-03-24 09:44
@gpeal Thanks for the solutions. But sadly it doesn't work for me, both solutions only scale the drawable itself while the LottieAnimationView stay the same size

**Comment by gpeal** [comment] 2022-01-14 04:27
@Luosoha I would recommend animating the layout params of the LottieAnimationView. If you resize the view, the animation inside will scale correctly. You can use scaleType centerCrop or centerInside, whichever is appropriate for your use case.

**Closed by gpeal** 2022-01-14 04:27 UTC
Labels: Non-Rendering Bug
