### ISSUE TITLE
Licensing is missing in pom

### ISSUE THREAD

**Issue by vanniktech** [airbnb/lottie-android#1884] opened 2021-08-30 10:10 UTC
I've started using [Licensee](https://github.com/cashapp/licensee) and with 4.1.1 when running `./gradlew licensee` I'm getting:

```
com.airbnb.android:lottie:4.1.0
 - ERROR: Artifact declares no licenses!
```

I've taken a look at the POM and indeed licenses are empty: https://search.maven.org/artifact/com.airbnb.android/lottie/4.1.0/aar

Looking at the [gradle.properties](https://github.com/airbnb/lottie-android/blob/05cb71817682b2f5361af5b98fb4a0bf2fdc82ae/gradle.properties#L29) it seems to be set, maybe it isn't picked up when you're publishing?

**Comment by gpeal** [comment] 2021-09-08 04:54
Duplicate of #1865

**Closed by gpeal** 2021-09-08 04:54 UTC
Labels: Non-Rendering Bug
