### ISSUE TITLE
From 3.0.6 animation froze instead of looping on activity startup

### ISSUE THREAD

**Issue by Tomekkk** [airbnb/lottie-android#1318] opened 2019-07-15 13:18 UTC
`LottieAnimationView` is define in xml layout file which is set as content view for Activity. Parameters set for view in layout:
```        
[...]
<com.airbnb.lottie.LottieAnimationView
          android:id="@+id/pulse"
          android:layout_width="32dp"
          android:layout_height="32dp"
          android:layout_marginEnd="16dp"
          android:layout_marginStart="16dp"
          app:layout_constraintBottom_toBottomOf="parent"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          app:lottie_autoPlay="true"
          app:lottie_fileName="pulse.json"
          app:lottie_loop="true"
          />
[...]
```
Starting from Lottie 3.0.6 across 3.0.7 this view stops animating at Activity's start. Configuration change or restoring Activity (moving from background) restores proper loop and autoplay behaviour.
From 3.0.0-beta4 to 3.0.5 the same lottie file seems to works fine.

Issue detected on Emulator Pixel 2 API 21 x86_64, replicated on OnePlus 6 API28

Lottie json file:
[pulse.json.zip](https://github.com/airbnb/lottie-android/files/3392426/pulse.json.zip)

**Comment by gpeal** [comment] 2019-07-20 03:46
@Tomekkk Can you create a sample project that reproduces this?

**Comment by Tomekkk** [comment] 2019-07-22 08:06
@gpeal repository: https://github.com/Tomekkk/LottieAnimationProblem
Please check screen recording:  https://raw.githubusercontent.com/Tomekkk/LottieAnimationProblem/master/screen-recording.webm 
LottieAnimationView is part of toolbar.

I didn't mention one important factor: lottie view is child of view set as shared element transition destination.

**Comment by Tomekkk** [comment] 2019-08-01 07:28
@gpeal do you need any more info? Can you reproduce issue on shared project?

**Comment by LukaszDzw** [comment] 2019-08-08 12:14
I have similar issue. On Samsung Galaxy s4 (Android 5.0.1) animation didn't started - blank area. It was happend only on the app start. On other Android phone there wasn't any problem

**Comment by gpeal** [comment] 2019-08-10 22:37
In this case, it seems to be a direct side effect of using a shared transition element. For now, I would manually play your animation rather than to rely on autoPlay. For some reason, the app bar is set to not visible the last time onVisiblityChanged or onVisibilityAggregated gets called on LottieAnimationView so it never knows that it is visible and able to play.

I'm going to close this since I don't have time to work on it but if you want to take a look, feel free to investigate the visibility callbacks when used in a shared element transition and open a PR if there is a reasonable solution.

**Closed by gpeal** 2019-08-10 22:37 UTC
