### ISSUE TITLE
Lottie animation works fine on the demo and player but on my phone it's still.

### ISSUE THREAD

**Issue by BugaIulian** [airbnb/lottie-android#693] opened 2018-03-19 10:29 UTC
Hey guys, I'm trying to get this working but I couldn't find any explanation on this matter. My animation it's pretty simple and it's working fine in the bodymovin player and on the web. I've even tried on lottie samples and it's working fine, but everytime I'm running it on the phone it stay's still and not playing.
I've attached a screenshot of the comp.
<img width="625" alt="screen shot 2018-03-19 at 10 27 36" src="https://user-images.githubusercontent.com/7817517/37590439-36df7856-2b60-11e8-8550-450a3d135aa3.png">
![screen shot 2018-03-19 at 10 28 30](https://user-images.githubusercontent.com/7817517/37590486-4ffbc222-2b60-11e8-955e-7e107645ea16.png)
![screen shot 2018-03-19 at 10 28 19](https://user-images.githubusercontent.com/7817517/37590487-501316b6-2b60-11e8-8541-0b22f8f4bdf9.png)

**Comment by gpeal** [comment] 2018-03-19 16:57
@BugaIulian If it works in the lottie sample app on Android but not in your app, you'll have to attach a sample project that repros this.

**Comment by BugaIulian** [comment] 2018-03-19 18:26
Thank you very much for your reply. I've attached the AE Project, the animation and the demo. I've spent hours on get it right but I can't find what's the problem.
[Archive.zip](https://github.com/airbnb/lottie-android/files/1826401/Archive.zip)

**Comment by gpeal** [comment] 2018-03-21 01:54
@BugaIulian text support in lottie is pretty basic right now. I plan on improving in in the future though.
In this case, the range selectors are likely the issue.
Duplicate of #485

**Closed by gpeal** 2018-03-21 01:54 UTC
