### ISSUE TITLE
Preview Error

### ISSUE THREAD

**Issue by ytsxg123** [airbnb/lottie-android#1956] opened 2021-11-30 03:01 UTC
inEditMode

java.lang.IllegalStateException: Asset repository is not set   at android.content.res.BridgeAssetManager.getAssetRepository(BridgeAssetManager.java:68)   at android.content.res.BridgeAssetManager.open(BridgeAssetManager.java:75)   at android.content.res.AssetManager.open(AssetManager.java:851)   at com.airbnb.lottie.manager.ImageAssetManager.bitmapForId(ImageAssetManager.java:108)   at com.airbnb.lottie.LottieDrawable.getImageAsset(LottieDrawable.java:1100)   at com.airbnb.lottie.model.layer.ImageLayer.getBitmap(ImageLayer.java:70)   at com.airbnb.lottie.model.layer.ImageLayer.drawLayer(ImageLayer.java:35)   at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:248)   at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:120)   at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:248)   at com.airbnb.lottie.LottieDrawable.drawWithOriginalAspectRatio(LottieDrawable.java:1297)   at com.airbnb.lottie.LottieDrawable.drawInternal(LottieDrawable.java:403)   at com.airbnb.lottie.LottieDrawable.draw(LottieDrawable.java:393)   at android.widget.ImageView.onDraw(ImageView.java:1436)   at android.view.View.draw_Original(View.java:22350)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:22323)   at android.view.View.buildDrawingCacheImpl(View.java:21623)   at android.view.View.buildDrawingCache(View.java:21483)   at com.airbnb.lottie.LottieAnimationView.buildDrawingCache(LottieAnimationView.java:1085)   at android.view.View.draw_Original(View.java:22073)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21995)   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)   at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)   at android.view.View.draw_Original(View.java:22353)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:22323)   at android.view.View.draw_Original(View.java:22223)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21995)   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)   at android.view.View.draw_Original(View.java:22221)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21995)   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)   at android.view.View.draw_Original(View.java:22221)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:21995)   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)   at android.view.View.draw_Original(View.java:22353)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:22323) Copy stack to clipboard

**Comment by gpeal** [comment] 2022-01-10 06:09
@ytsxg123 Can you attach a repro project? Which version of Android Studio was this on? I just tried with an animation that has images and set the imageAssetFolder in XML and it was able to render it in the layout preview?

**Comment by gpeal** [comment] 2022-01-16 19:19
I'm going to close this since it may have been fixed on the Android Studio side. Let me know if you can still reproduce it on Bumble Bee or later.

**Closed by gpeal** 2022-01-16 19:19 UTC
Labels: Needs more info
