### ISSUE TITLE
App suddenly stopped While Loading a URL. 

### ISSUE THREAD

**Issue by wanizubair** [airbnb/lottie-android#712] opened 2018-03-31 13:13 UTC
#### Expected behavior

+ The App should be able to Load URL. 

#### Actual behavior

+ The App is not able to load URL, When I enter URL and click on load app suddenly stopped after few seconds of loading. 

#### How to reproduce

+ Launch the App. 

+ Click on Preview icon. 

+ Click on Enter a URL to a jason or zip file 

+ Enter URL

+ Click on load option, after few seconds of loading app suddenly stopped. 

* Application : Lottie, Version :2.5.2

* Operating system:Android Nouaght (7.0)

#### Recording Of The Bug
https://youtu.be/Ei8V5eM1-CY   

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/app-suddenly-stopped-while-loading-a-url">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gpeal** [comment] 2018-04-08 00:10
Duplicate of #710

**Closed by gpeal** 2018-04-08 00:10 UTC
