### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by someoneIG** [airbnb/lottie-android#1901] opened 2021-09-14 12:42 UTC
Hi, my app crashes on some devices
I attach the log photos and put the text of the log under it.

1. https://pasteboard.co/ZdMqfHaNFSTM.png

````
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:550)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:137)
       at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:76)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:89)
       at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:160)
       at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:213)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:459)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment.status(HomeFragment.java:516)
       at com.megavpn.mega.fragment.HomeFragment.prepareVpn(HomeFragment.java:354)
       at com.megavpn.mega.fragment.HomeFragment.access$200(HomeFragment.java:70)
       at com.megavpn.mega.fragment.HomeFragment$3.onResponseSuccess(HomeFragment.java:289)
       at com.megavpn.mega.fragment.HomeFragment$3.onResponseSuccess(HomeFragment.java:281)
       at com.megavpn.mega.remote.Repository$6.onResponse(Repository.java:154)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
       at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(:6)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
````

2. https://pasteboard.co/k3Ab68V1ziE7.png

````
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at com.airbnb.lottie.value.Keyframe.containsProgress(Keyframe.java:125)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation$KeyframesWrapperImpl.isValueChanged(BaseKeyframeAnimation.java:297)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:62)
       at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.setProgress(TransformKeyframeAnimation.java:127)
       at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:550)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:155)
       at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:76)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:89)
       at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:160)
       at com.airbnb.lottie.LottieDrawable.setFrame(LottieDrawable.java:795)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:462)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment.status(HomeFragment.java:516)
       at com.megavpn.mega.fragment.HomeFragment.setStateShadowsocks(HomeFragment.java:242)
       at com.megavpn.mega.fragment.HomeFragment.stateChanged(HomeFragment.java:405)
       at com.github.shadowsocks.aidl.ShadowsocksConnection$serviceCallback$1$stateChanged$1.invokeSuspend(ShadowsocksConnection.kt:73)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
````

3. https://pasteboard.co/KTtQYl6H5W42.png

````
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation$KeyframesWrapperImpl.findKeyframe(BaseKeyframeAnimation.java:305)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation$KeyframesWrapperImpl.isValueChanged(BaseKeyframeAnimation.java:300)
       at com.airbnb.lottie.animation.keyframe.BaseKeyframeAnimation.setProgress(BaseKeyframeAnimation.java:62)
       at com.airbnb.lottie.animation.keyframe.TransformKeyframeAnimation.setProgress(TransformKeyframeAnimation.java:127)
       at com.airbnb.lottie.model.layer.BaseLayer.setProgress(BaseLayer.java:557)
       at com.airbnb.lottie.model.layer.CompositionLayer.setProgress(CompositionLayer.java:155)
       at com.airbnb.lottie.LottieDrawable$1.onAnimationUpdate(LottieDrawable.java:76)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyUpdate(BaseLottieAnimator.java:89)
       at com.airbnb.lottie.utils.LottieValueAnimator.setFrame(LottieValueAnimator.java:160)
       at com.airbnb.lottie.utils.LottieValueAnimator.playAnimation(LottieValueAnimator.java:213)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:459)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment$2.onAnimationEnd(HomeFragment.java:207)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
       at com.airbnb.lottie.utils.BaseLottieAnimator.notifyEnd(BaseLottieAnimator.java:74)
       at com.airbnb.lottie.utils.LottieValueAnimator.endAnimation(LottieValueAnimator.java:222)
       at com.airbnb.lottie.LottieDrawable.playAnimation(LottieDrawable.java:463)
       at com.airbnb.lottie.LottieAnimationView.playAnimation(LottieAnimationView.java:636)
       at com.megavpn.mega.fragment.HomeFragment.status(HomeFragment.java:516)
       at com.megavpn.mega.fragment.HomeFragment.setStateShadowsocks(HomeFragment.java:242)
       at com.megavpn.mega.fragment.HomeFragment.stateChanged(HomeFragment.java:405)
       at com.github.shadowsocks.aidl.ShadowsocksConnection$serviceCallback$1$stateChanged$1.invokeSuspend(ShadowsocksConnection.kt:73)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
````

**Comment by gpeal** [comment] 2021-09-14 16:34
Duplicate of #1534 
https://github.com/airbnb/lottie-android/issues/1534#issuecomment-719997163

**Closed by gpeal** 2021-09-14 16:34 UTC
