### ISSUE TITLE
Font rendering issue for hindi (non-latin) characters

### ISSUE THREAD

**Issue by mmdumi** [airbnb/lottie-android#1779] opened 2021-03-31 10:57 UTC
**Describe the bug**
We're trying to render hindi characters that are inserted at runtime with TextDelegate support:
`setText("///trail.feast.beam", "///बादल.मीठा.अमूल्य")`
As you can see in the attached screenshot and project, some characters are not rendered correctly. Android seems to have a default fallback to always render unicode characters but in lottie's case this doesn't happen.
What do you think about this issue, how exactly should we approach this ?

**What version of Lottie did you test this on?**
Latest lottie android 3.6.1

**What version of Android did you test this on?**
Android 10, Pixel 2 XL

**Steps To Reproduce**
Attached a project where you can see the issue:
[MyApplication.zip](https://github.com/airbnb/lottie-android/files/6235991/MyApplication.zip)

**Screenshots**
![Screenshot_20210331-134645](https://user-images.githubusercontent.com/189993/113133625-8d2fcf80-9228-11eb-8f91-5a1470865254.png)

**Comment by gpeal** [comment] 2021-03-31 19:48
Duplicate of #1396

**Closed by gpeal** 2021-03-31 19:48 UTC
Labels: Rendering bug
