### ISSUE TITLE
Text Layer is not positioning correctly on Android

### ISSUE THREAD

**Issue by krishnasajja** [airbnb/lottie-android#481] opened 2017-09-28 19:26 UTC
I'm trying to animate images as well as some text, which I want to change dynamically. I notice that the images are positioned correctly on Android device while the text is off to the right. 

Output Screenshot:

![screenshot_1506626350](https://user-images.githubusercontent.com/3412611/30986146-18359ee2-a458-11e7-8911-85a5cc11be2b.png)

Here is the json file that we are using.
[android_text_test.json.zip](https://github.com/airbnb/lottie-android/files/1342045/android_text_test.json.zip)

AE screens:

![1506625960](https://user-images.githubusercontent.com/3412611/30986046-d8ac1d00-a457-11e7-81c3-33fd067aad10.png)
<img width="961" alt="1506625968" src="https://user-images.githubusercontent.com/3412611/30986048-db63b076-a457-11e7-9255-66936067441f.png">

Also, I notice that if I set the LottieAnimationView's width and height as fixed and square, like 300dp and 300dp, it seem to be positioning the text correctly. This is how I'm using.

    <com.airbnb.lottie.LottieAnimationView
        android:id="@+id/animation_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:scaleType="centerInside"
        app:lottie_loop="true"/>

Do you have any recommended way of setting up TextLayers in AE so that Lottie positions correctly? Is there any aspect ratio that we need to follow? Thanks!

**Comment by gpeal** [comment] 2017-10-22 15:10
@krishnasajja Can you attach the aep?

**Comment by krishnasajja** [comment] 2017-10-23 14:59
[android_text_test.zip](https://github.com/airbnb/lottie-android/files/1407622/android_text_test.zip)


Here's the AEP file and the json file.

**Comment by krishnasajja** [comment] 2017-11-06 05:04
Hi..Any updates on this issue?

**Comment by gpeal** [comment] 2017-11-06 18:21
@krishnasajja I have some plans to revisit text rendering but I haven't had the chance to yet. I'd accept PRs too.

**Comment by krishnasajja** [comment] 2017-11-06 20:44
@gpeal Sure. Thank you for the update!

**Comment by krishnasajja** [comment] 2018-01-03 22:50
@gpeal I'm looking into the lottie code to find the issue. I'm not sure what different keys mean in the JSON file. Do you have a list of the key mappings? Like 'nm' is name, 't' is text etc.

I'm planning to track the usage of the keys to find out if there are any issues there. Thanks!

**Comment by gpeal** [comment] 2018-01-03 23:23
@krishnasajja https://github.com/airbnb/lottie-web/blob/master/docs/json/layers/text.json

**Comment by panzhi1** [comment] 2018-09-03 05:53
Is there a solution to this problem?

**Comment by gpeal** [comment] 2018-12-09 22:06
Duplicate of #388

**Closed by gpeal** 2018-12-09 22:06 UTC
Labels: Text
