### ISSUE TITLE
My animation doesn't work. Show nothing on my view.

### ISSUE THREAD

**Issue by libill** [airbnb/lottie-android#2450] opened 2024-01-19 07:00 UTC
[单独礼花.json](https://github.com/airbnb/lottie-android/files/13985470/default.json)

My animation doesn't work. Show nothing on my view. But web and iOS can play this animation.

[Version] Lottie android 6.3.0

**Comment by gpeal** [comment] 2024-03-04 03:23
Duplicate of #257

**Closed by gpeal** 2024-03-04 03:23 UTC
Labels: Rendering bug
