### ISSUE TITLE
Lottie is cutting animation from the right side

### ISSUE THREAD

**Issue by pasha656** [airbnb/lottie-android#1314] opened 2019-07-12 05:11 UTC
We have an issue with one file, which is cutting from the right side.

<img width="500" alt="Screen+Shot+2019-07-11+at+16 39 02" src="https://user-images.githubusercontent.com/10083521/61103835-6215b300-a47c-11e9-82fc-bb3315a090d0.png">

The issue occurs on all Lottie versions after v3.0.0-beta2.
If I switch the project to 2.7.0 - everything works fine.

Animation example you can find here: [Example](https://github.com/pasha656/CustomView/blob/master/screenshots/PIN_example.json)

**Comment by SemenovAlexander** [comment] 2019-07-12 07:06
This seems to be related to #1313

**Comment by ming13** [comment] 2019-07-15 05:29
FYI — `2.8.0` also works fine.

**Comment by gpeal** [comment] 2019-07-15 17:59
Duplicate of #1287

**Closed** 2019-07-20 03:45 UTC
