### ISSUE TITLE
Unable to parse composition

### ISSUE THREAD

**Issue by NewOrin** [airbnb/lottie-android#1080] opened 2019-01-09 06:39 UTC
Hi, gays. I have a crash on my release app. Crashes rarely happen, I can't reproduce myself. Lottie version is v2.7.0.  and it's only happened in android 8.0 devices.
Here is the log.

` Crashed: main
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:68)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:66)
       at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:167)
       at com.airbnb.lottie.LottieTask.access$000(LottieTask.java:26)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:142)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:7015)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

Fatal Exception: java.lang.IllegalStateException: Unable to parse composition
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:68)
       at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:66)
       at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:167)
       at com.airbnb.lottie.LottieTask.access$000(LottieTask.java:26)
       at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:142)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:198)
       at android.app.ActivityThread.main(ActivityThread.java:7015)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:521)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

Caused by java.util.concurrent.ExecutionException: java.lang.AssertionError
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at com.airbnb.lottie.LottieTask$2.run(LottieTask.java:189)

Caused by java.lang.AssertionError
       at android.util.JsonReader.peek(JsonReader.java:363)
       at android.util.JsonReader.expect(JsonReader.java:308)
       at android.util.JsonReader.beginObject(JsonReader.java:293)
       at com.airbnb.lottie.parser.LottieCompositionParser.parse(LottieCompositionParser.java:42)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonReaderSync(LottieCompositionFactory.java:229)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:163)
       at com.airbnb.lottie.LottieCompositionFactory.fromJsonInputStreamSync(LottieCompositionFactory.java:157)
       at com.airbnb.lottie.LottieCompositionFactory.fromRawResSync(LottieCompositionFactory.java:129)
       at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:116)
       at com.airbnb.lottie.LottieCompositionFactory$2.call(LottieCompositionFactory.java:114)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

Thanks a lot!

**Comment by gpeal** [comment] 2019-01-15 17:30
@NewOrin Please attach the animation

**Comment by Abelzzg** [comment] 2019-01-31 02:04
I have the same crash,this's my animation

`{"v":"5.4.1","fr":30,"ip":0,"op":20,"w":60,"h":42,"nm":"1","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"不动腿","parent":5,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[44.125,468.375,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.242,10.242],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"椭圆路径 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.76862745098,0.035294117647,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-40.32,-442.248],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[50,50],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"椭圆 5","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.242,10.242],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"椭圆路径 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.76862745098,0.035294117647,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-49.536,-441.277],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[50,50],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"椭圆 4","np":2,"cix":2,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.242,10.242],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"椭圆路径 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.76862745098,0.035294117647,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-58.276,-441.832],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[50,50],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"椭圆 3","np":2,"cix":2,"ix":3,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.242,10.242],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"椭圆路径 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.76862745098,0.035294117647,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-30.331,-444.918],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"椭圆 6","np":2,"cix":2,"ix":4,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[10.242,10.242],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"椭圆路径 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.76862745098,0.035294117647,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-68.666,-446.491],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"椭圆 2","np":2,"cix":2,"ix":5,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":21,"st":0,"bm":0},{"ddd":0,"ind":2,"ty":4,"nm":"saihong","parent":5,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[12,-5.25,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"d":1,"ty":"el","s":{"a":0,"k":[19.113,7.044],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"nm":"椭圆路径 1","mn":"ADBE Vector Shape - Ellipse","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.352941176471,0.352941176471,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[-5.362,3.373],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"椭圆 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":3,"ty":4,"nm":"eye","parent":5,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[-10,-8.75,0],"ix":2},"a":{"a":0,"k":[-8.375,-475,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"n":"0p833_0p833_0p167_0p167","t":7,"s":[{"i":[[1.75,-0.018],[0.172,-0.828],[0,0],[0.031,-0.031],[-0.266,-0.344],[-0.25,-0.188],[-1.656,0.043],[-0.19,0.163],[0,0],[0,0],[0,0],[0.282,0.672]],"o":[[-2.141,0.022],[-0.156,0.75],[0,0],[0.062,0.141],[0,0],[0.234,0.094],[1.203,-0.031],[0.142,-0.141],[0,0],[0,0],[0,0],[-0.39,-0.688]],"v":[[-8.656,-482.029],[-11.75,-479.969],[-11.906,-477.969],[-11.828,-477.562],[-11.172,-476.469],[-10.516,-476.016],[-8.281,-475.641],[-6.298,-476.266],[-5.813,-476.797],[-5.516,-477.428],[-5.36,-478.375],[-5.657,-480.375]],"c":true}],"e":[{"i":[[2.875,-0.062],[-0.062,-0.812],[0,0],[-0.5,0],[0,0],[-0.062,0.688],[-2.062,0.062],[-0.062,-0.562],[0,0],[0,0],[0,0],[0.125,0.75]],"o":[[-3.249,0.071],[0.062,0.812],[0,0],[0.5,0],[0,0],[0.062,-0.688],[2.062,-0.062],[0.062,0.562],[0,0],[0,0],[0,0],[-0.125,-0.75]],"v":[[-8.625,-483.625],[-12.875,-480.062],[-12.812,-475.688],[-12,-475.438],[-11.125,-475.688],[-11.188,-479.312],[-8.625,-481.625],[-6.062,-479.375],[-5.875,-475.562],[-4.937,-475.35],[-4.188,-475.625],[-4.188,-479.875]],"c":true}]},{"t":17}],"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.164705882353,0.117647058824,0.078431372549,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"形状 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":281,"st":-19,"bm":0},{"ddd":0,"ind":4,"ty":4,"nm":"zhuangshi","parent":5,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[0,0,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[1.844,0.062],[0,0],[0.002,-0.499],[1.834,-1.215],[4.477,-0.026],[0,0],[-6.375,0.125],[0,0],[0,0]],"o":[[-0.094,0],[0,0],[-0.12,1.052],[-10.541,1.41],[2.972,2.005],[0,0],[6.375,-0.125],[0,0],[0,0]],"v":[[9.062,-25.75],[5.625,-25.75],[5.623,9.624],[3.791,14.465],[-17.727,15.526],[-11.875,17.875],[5.5,17.75],[10.75,9.75],[10.75,-23.562]],"c":true},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[0.972549019608,0.666666666667,0.027450980392,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"形状 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":5,"ty":4,"nm":"body","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[29,40.125,0],"ix":2},"a":{"a":0,"k":[-5,27.5,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":0,"s":[0,0,100],"e":[50,50,100]},{"t":14}],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":0,"k":{"i":[[2.438,0.062],[0,0],[-1.125,-0.875],[-1.625,-3.125],[0.125,-10.75],[0,0],[-6.375,0.125],[0,0],[0,0]],"o":[[-0.062,-0.062],[0,0],[1.125,0.875],[2.75,6.25],[0.75,13.25],[0,0],[6.375,-0.125],[0,0],[0,0]],"v":[[8.562,-25.75],[-33.125,-25.75],[-33,-24.375],[-24,-19],[-24.125,3.25],[-11.875,17.875],[5.5,17.75],[10.75,9.75],[10.75,-23.5]],"c":true},"ix":2},"nm":"路径 1","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.807843137255,0,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[0,0],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"形状 1","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":300,"st":0,"bm":0},{"ddd":0,"ind":6,"ty":4,"nm":"head","parent":5,"sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[12.75,-26.778,0],"ix":2},"a":{"a":0,"k":[14.5,-492,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"shapes":[{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[8,15],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":2,"ix":4},"nm":"矩形路径 1","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.292264093137,0.292264093137,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[15.94,-493.71],"ix":2},"a":{"a":0,"k":[0.042,8.474],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":45,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"矩形 3","np":2,"cix":2,"ix":1,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[7,17],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":2,"ix":4},"nm":"矩形路径 1","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.292264093137,0.292264093137,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[22.352,-495.252],"ix":2},"a":{"a":0,"k":[0,0],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":90,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"矩形 2","np":2,"cix":2,"ix":2,"mn":"ADBE Vector Group","hd":false},{"ty":"gr","it":[{"ty":"rc","d":1,"s":{"a":0,"k":[7,17],"ix":2},"p":{"a":0,"k":[0,0],"ix":3},"r":{"a":0,"k":2,"ix":4},"nm":"矩形路径 1","mn":"ADBE Vector Shape - Rect","hd":false},{"ty":"fl","c":{"a":0,"k":[1,0.292264093137,0.292264093137,1],"ix":4},"o":{"a":0,"k":100,"ix":5},"r":1,"nm":"填充 1","mn":"ADBE Vector Graphic - Fill","hd":false},{"ty":"tr","p":{"a":0,"k":[13.309,-500.115],"ix":2},"a":{"a":0,"k":[-4.025,0.121],"ix":1},"s":{"a":0,"k":[100,100],"ix":3},"r":{"a":0,"k":0,"ix":6},"o":{"a":0,"k":100,"ix":7},"sk":{"a":0,"k":0,"ix":4},"sa":{"a":0,"k":0,"ix":5},"nm":"变换"}],"nm":"矩形 1","np":2,"cix":2,"ix":3,"mn":"ADBE Vector Group","hd":false}],"ip":0,"op":281,"st":-19,"bm":0}],"markers":[]}`

**Comment by Ma-lian** [comment] 2019-02-02 03:46
I also have this crash,because I have two json files in raws and i load them in the same time,this will cause two threads operate one arrayList in the same time。so the solution is i load them by using LoadAnimationView.addLottieOnCompositionLoadedListeneadd to make sure load them in order!

**Comment by gpeal** [comment] 2019-02-02 20:06
@Ma-lian which ArrayList are you referring to?

**Comment by gpeal** [comment] 2019-02-21 16:30
Duplicate of #667

**Closed by gpeal** 2019-02-21 16:30 UTC

**Comment by 1wayticket** [comment] 2019-03-13 03:00
> I also have this crash,because I have two json files in raws and i load them in the same time,this will cause two threads operate one arrayList in the same time。so the solution is i load them by using LoadAnimationView.addLottieOnCompositionLoadedListeneadd to make sure load them in order!

I have the same usage with you--I have 3 LottieAnimationView loaded at the same time.But I didn't find the reason why crash happend. So can you give more details? Thanks a lot anyway.

**Comment by zhulk3** [comment] 2020-07-02 08:52
> > I also have this crash,because I have two json files in raws and i load them in the same time,this will cause two threads operate one arrayList in the same time。so the solution is i load them by using LoadAnimationView.addLottieOnCompositionLoadedListeneadd to make sure load them in order!
> 
> I have the same usage with you--I have 3 LottieAnimationView loaded at the same time.But I didn't find the reason why crash happend. So can you give more details? Thanks a lot anyway.

I also want to no why it crashed.

**Comment by chanjungkim** [comment] 2020-10-13 08:37
Check if you have the file. It can occur when the JSON file doesn't exist.
