### ISSUE TITLE
Crash in Lottie with NPE in BaseStrokeContent

### ISSUE THREAD

**Issue by softcrafter** [airbnb/lottie-android#759] opened 2018-05-09 13:05 UTC
**Environment:** 
Lottie: 2.5.0 
Android OS: 4.3.1
Device: Galaxy Nexus (Emulator)

**Steps**
Just load the load the animation: https://www.lottiefiles.com/download/1830

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at com.airbnb.lottie.animation.content.BaseStrokeContent.<init>(BaseStrokeContent.java:61)
                      at com.airbnb.lottie.animation.content.StrokeContent.<init>(StrokeContent.java:25)
                      at com.airbnb.lottie.model.content.ShapeStroke.toContent(ShapeStroke.java:77)
                      at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
                      at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
                      at com.airbnb.lottie.model.content.ShapeGroup.toContent(ShapeGroup.java:29)
                      at com.airbnb.lottie.animation.content.ContentGroup.contentsFromModels(ContentGroup.java:30)
                      at com.airbnb.lottie.animation.content.ContentGroup.<init>(ContentGroup.java:60)
                      at com.airbnb.lottie.model.layer.ShapeLayer.<init>(ShapeLayer.java:25)
                      at com.airbnb.lottie.model.layer.BaseLayer.forModel(BaseLayer.java:44)
                      at com.airbnb.lottie.model.layer.CompositionLayer.<init>(CompositionLayer.java:52)
                      at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:225)
                      at com.airbnb.lottie.LottieDrawable.setComposition(LottieDrawable.java:187)
                      at com.airbnb.lottie.LottieAnimationView.setComposition(LottieAnimationView.java:468)
```

**Comment by HunkD** [comment] 2018-06-28 01:50
any update on this? our app reports much crash due to this issue.

**Comment by Jakst** [comment] 2018-06-28 11:01
@HunkD You can downgrade to 2.3.2 to avoid the crash

**Comment by gpeal** [comment] 2018-06-28 19:39
@HunkD Is there any chance that you are trying to load several Lottie animations at once?

**Comment by gpeal** [comment] 2018-06-28 19:39
@HunkD My suspicion is that some OEM implementations of JsonReader aren't thread safe.

**Comment by gpeal** [comment] 2018-06-29 02:56
@HunkD Can you attach a project that repros this?

**Comment by HunkD** [comment] 2018-06-29 07:01
@gpeal https://github.com/HunkD/LottieCrash

**Comment by softcrafter** [comment] 2018-06-29 08:28
Hi @gpeal,

Just a note here, I am not loading more than one animation at once and I still encounter the crash.

**Comment by gpeal** [comment] 2018-07-09 06:41
@softcrafter I was unable to reproduce this down to API 16. Please attach a sample project.

@HunkD Your project pertains to https://github.com/react-community/lottie-react-native/

**Comment by yk3372** [comment] 2018-07-16 09:50
this maybe help you #351

**Comment by softcrafter** [comment] 2018-09-13 13:35
@gpeal, I found out the strange thing about this bug, so it only reproduces when you convert the animation string to JSONObject and convert it back:
```java
public String loadJSONFromAsset() {
        String json = null;
        try {
            InputStream is = getAssets().open("done.json");
            int size = is.available();
            byte[] buffer = new byte[size];
            is.read(buffer);
            is.close();
            json = new String(buffer, "UTF-8");
        } catch (IOException ex) {
            ex.printStackTrace();
            return null;
        }

       //If you comment this, the bug will not reproduce
        try {
            JSONObject jsonObject = new JSONObject(json);
            json = jsonObject.toString();
        }
        catch (JSONException e) {
            e.printStackTrace();
        }

        return json;
    }
```

The UI component that I provide gets the animation as in a JSONObject and when I convert the json back to a string the order of the fields are not the same? Is the order important ?

Thanks,
Cristian

**Comment by softcrafter** [comment] 2018-09-13 13:44
PS. The order is only messed up on devices using API <=19

**Comment by softcrafter** [comment] 2018-09-13 14:13
P.S. 2:
Looked into the code and tried to see what is wrong. So after converting to json and back this element looks like this:
Before
```json
            {
              "ty": "st",
              "c": {
                "a": 0,
                "k": [
                  1,
                  1,
                  1,
                  1
                ],
                "ix": 3
              },
              "o": {
                "a": 0,
                "k": 100,
                "ix": 4
              },
              "w": {
                "a": 0,
                "k": 0,
                "ix": 5
              },
              "lc": 1,
              "lj": 1,
              "ml": 4,
              "nm": "Stroke 1",
              "mn": "ADBE Vector Graphic - Stroke",
              "hd": false
            },
```
After
```json
{
              "mn": "ADBE Vector Graphic - Stroke",
              "w": {
                "k": 0,
                "ix": 5,
                "a": 0
              },
              "ty": "st",
              "lj": 1,
              "c": {
                "k": [
                  1,
                  1,
                  1,
                  1
                ],
                "ix": 3,
                "a": 0
              },
              "o": {
                "k": 100,
                "ix": 4,
                "a": 0
              },
              "hd": false,
              "lc": 1,
              "ml": 4,
              "nm": "Stroke 1"
            },
```

What is important here is the position of the "ty": "st" because all the fields before that element will be lost (This is how the algorithm work from ShapeStrokeParser). This is why the width is not set and NPE is happening.

**Comment by gpeal** [comment] 2018-09-21 16:03
@softcrafter oh wow, very interesting. I'll reopen this but I'm not sure I'll be able to get to it that soon. Can you try and use the string directly in the meantime?

**Comment by softcrafter** [comment] 2018-09-21 16:05
@gpeal, thanks. Yes we will use the String as it is for know.

**Comment by gpeal** [comment] 2018-09-24 06:04
I'm going to close this as the above seems like a platform bug that Lottie can't do anything about. The next version of Lottie won't even accept JsonObjects anymore and it is discouraged to use them at any point in the pipeline because it purely adds overhead.

**Closed by gpeal** 2018-09-24 06:04 UTC
