### ISSUE TITLE
Animation not appearing correctly when implemented

### ISSUE THREAD

**Issue by Puranjai256** [airbnb/lottie-android#2202] opened 2022-12-07 10:53 UTC
This animation was created using Adobe After Effects 2023 and Lottie extension 3.1.1
The app uses Lottie 3.4.1 with Android SDK, which supports a maximum version of 32

Below are two videos that demonstrate the differences in animation:

Video 1 - Lottie animation was created in After Effects. Take note of the insignia over the word Buck. The shape is outlined and then filled with red color. The byline- "Tarakki ka naya tarika" is aligned in the middle of the Logo- BlackBuck

Video 2 -  No modifications were made to this Lottie. Android SDK version 32, Lottie 3.4.1. Instead of an outline and fill animation, the insignia over Buck just fades in. The byline "Tarakki ka naya tarika" is slightly off-center and not aligned with the logo BlackBuck.

https://user-images.githubusercontent.com/63489120/206160300-b83fcdea-cd3d-4415-ba7a-dbbb07b18351.mp4

https://user-images.githubusercontent.com/63489120/206160326-18707275-6628-475f-bb0a-8c31014d1376.mp4

**Comment by gpeal** [comment] 2022-12-07 19:17
You're using a very old version of Lottie. Can you try 5.2.0 or 5.3.0-SNAPSHOT?

**Comment by gpeal** [comment] 2022-12-07 19:57
Duplicate of #2202

**Closed by gpeal** 2022-12-07 19:57 UTC
Labels: Non-Rendering Bug
