### ISSUE TITLE
Caused by: java.net.ConnectException: Failed to connect to img.shengdianhuadk.com/120.233.75.41:443

### ISSUE THREAD

**Issue by wz1993** [airbnb/lottie-android#1477] opened 2020-01-09 10:01 UTC
java.lang.IllegalStateException: Unable to parse composition
    at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:75)
    at com.airbnb.lottie.LottieAnimationView$2.onResult(LottieAnimationView.java:73)
    at com.airbnb.lottie.LottieTask.notifyFailureListeners(LottieTask.java:158)
    at com.airbnb.lottie.LottieTask.access$200(LottieTask.java:27)
    at com.airbnb.lottie.LottieTask$1.run(LottieTask.java:133)
    at android.os.Handler.handleCallback(Handler.java:888)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8147)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.net.ConnectException: Failed to connect to img.shengdianhuadk.com/120.233.75.41:443
    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:94)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:79)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:48)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:31)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:71)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)
java.net.ConnectException: Failed to connect to img.shengdianhuadk.com/120.233.75.41:443
    at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
    at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
    at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
    at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
    at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
    at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
    at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetworkInternal(NetworkFetcher.java:94)
    at com.airbnb.lottie.network.NetworkFetcher.fetchFromNetwork(NetworkFetcher.java:79)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:48)
    at com.airbnb.lottie.network.NetworkFetcher.fetchSync(NetworkFetcher.java:31)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:71)
    at com.airbnb.lottie.LottieCompositionFactory$1.call(LottieCompositionFactory.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:929)

**Comment by gpeal** [comment] 2020-01-10 18:51
Duplicate of #1479

**Closed by gpeal** 2020-01-10 18:51 UTC
