### ISSUE TITLE
LottieDrawable with images convert to Video, Images not display

### ISSUE THREAD

**Issue by diguagege** [airbnb/lottie-android#1311] opened 2019-07-11 09:20 UTC
Hi, I have a problem in use LottieDrawable convert to Media.
I have a  json and images folder in assets, When I open app, I load json with setImagesAssetsFolder to composition, and then into static LottieDrawable.
And I write a tool , convert LottieDrawable to video. And finally, I mux a video out to folder. But when I open the video, It may play with images no display. How can I fix it ?
![6E294058DD11E6CA4CF5123BB91B3031](https://user-images.githubusercontent.com/6269201/61039638-bd568f80-a401-11e9-8cea-2c67a1f7dd18.jpg)

![75CD5713EBEE5E721B2A2F424EA2BDC0](https://user-images.githubusercontent.com/6269201/61039661-c5163400-a401-11e9-813e-0ee70bf0ebc7.jpg)

**Comment by gpeal** [comment] 2019-07-19 20:05
Duplicate of #1273

**Closed by gpeal** 2019-07-19 20:05 UTC

**Comment by diguagege** [comment] 2019-07-24 07:28
> Duplicate of #1273

No, sir, #1273 can not solve my problem.But I find the problem because I dont pass the view to lottie to get context, and then lottie cannot read img from settings.

**Comment by krish-ktm** [comment] 2022-02-01 16:11
@diguagege I have same problem can you share code ?
