### ISSUE TITLE
Play once then loop from frame to frame

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-android#425] opened 2017-08-08 22:36 UTC
Before opening a new issue:

Is it possible to loop an animation once and then call the same animation to loop from e.g. frame 25 to frame 300? I've been looking for documentation in the issues and haven't been able to locate anything. any help would be appreciated.

**Comment by gpeal** [comment] 2017-08-10 00:47
We're going to add an API to do this but in the mean time, you can create your own ValueAnimator that animates from the progress equivalent of frame 25 and frame 300 and set the progress of the animation in the animation listener.

Under the hood, Lottie just uses a ValueAnimator from 0 to 1 to play an animation.

**Comment by gpeal** [comment] 2017-08-10 00:47
Duplicate of https://github.com/airbnb/lottie-android/issues/415

**Closed by gpeal** 2017-08-10 00:47 UTC

**Comment by jianjonathanyang** [comment] 2019-01-12 00:39
@gpeal What is the API added for looping from a specific frame?

**Comment by gpeal** [comment] 2019-01-12 02:44
@jianjonathanyang `setMinFrame` and `setMaxFrame`
