### ISSUE TITLE
Animation not displyed correctly on API26 starting from version 3.0.0

### ISSUE THREAD

**Issue by Messady** [airbnb/lottie-android#1287] opened 2019-06-25 10:36 UTC
**Tested on:**
Emulator: Nexus 5X API 26
Device: LG G6 API26

**Issue:**
Starting from version 3.0.0, the animation is not rendered as it used to be on API26.

**Lottie file:**
https://drive.google.com/open?id=1oGzaRrBGnjCIvL0DBz_8Q3WfSKpSDq4p

**Preview:**
![Api26Issue](https://user-images.githubusercontent.com/599191/60091793-b2370a80-9745-11e9-9e22-79b6f6d05292.jpg)

**Comment by gpeal** [comment] 2019-07-15 17:59
@Messady  @SemenovAlexander is there an emulator image you can repro this on?

**Comment by gpeal** [comment] 2019-07-15 17:59
@pasha656 @ming13 same question ^

**Comment by gpeal** [comment] 2019-07-16 05:15
Duplicate of #1253

**Closed by gpeal** 2019-07-16 05:15 UTC
